// Code generated by scripts/gen_bindings; DO NOT EDIT.

package app

import (
	"github.com/gaea/gaea/internal/herdsman"
	"github.com/gaea/gaea/internal/modelengine"
)

// ModelB 模型中心与 Herdsman 底座绑定门面（S2-3「App 绑定面拆分」）：仅暴露模型中心与 Herdsman 底座的方法，
// 方法体零改动——纯委托给 App 实例（b.a.<Method>）。
type ModelB struct{ a *App }

func (b *ModelB) GaeaBenchmarkDetail(id string) (BenchmarkRunDetail, error) { return b.a.GaeaBenchmarkDetail(id) }
func (b *ModelB) GaeaBenchmarkExport(id string, dir string) (string, error) { return b.a.GaeaBenchmarkExport(id, dir) }
func (b *ModelB) GaeaBenchmarkList() ([]BenchmarkRunSummary, error) { return b.a.GaeaBenchmarkList() }
func (b *ModelB) GaeaBenchmarkStart(req BenchmarkRequest) (string, error) { return b.a.GaeaBenchmarkStart(req) }
func (b *ModelB) GaeaEngines() []modelengine.EngineConfig { return b.a.GaeaEngines() }
func (b *ModelB) GaeaGetUsdCnyRate() float64 { return b.a.GaeaGetUsdCnyRate() }
func (b *ModelB) GaeaModel() string { return b.a.GaeaModel() }
func (b *ModelB) GaeaModelSwitchEstimate(engineID string) ModelSwitchEstimate { return b.a.GaeaModelSwitchEstimate(engineID) }
func (b *ModelB) GaeaModels() []ModelInfo { return b.a.GaeaModels() }
func (b *ModelB) GaeaSetEngine(engineID string) error { return b.a.GaeaSetEngine(engineID) }
func (b *ModelB) GaeaSetModel(name string) error { return b.a.GaeaSetModel(name) }
func (b *ModelB) GaeaSetUsdCnyRate(rate float64) error { return b.a.GaeaSetUsdCnyRate(rate) }
func (b *ModelB) GaeaUsageOverview() UsageOverview { return b.a.GaeaUsageOverview() }
func (b *ModelB) GetActiveEngine() string { return b.a.GetActiveEngine() }
func (b *ModelB) GetActiveModel() string { return b.a.GetActiveModel() }
func (b *ModelB) GetEngines() []modelengine.EngineConfig { return b.a.GetEngines() }
func (b *ModelB) GetModelMonitor() map[string]interface{} { return b.a.GetModelMonitor() }
func (b *ModelB) GetModelRoute(feature string) (string, error) { return b.a.GetModelRoute(feature) }
func (b *ModelB) GetOfficeLocal() bool { return b.a.GetOfficeLocal() }
func (b *ModelB) GetSensitiveLocal() bool { return b.a.GetSensitiveLocal() }
func (b *ModelB) HerdsmanDigitalLife() (HerdsmanDigitalLife, error) { return b.a.HerdsmanDigitalLife() }
func (b *ModelB) HerdsmanHealth() herdsman.HealthResult { return b.a.HerdsmanHealth() }
func (b *ModelB) HerdsmanLaunchPresets() ([]HerdsmanLaunchPreset, error) { return b.a.HerdsmanLaunchPresets() }
func (b *ModelB) HerdsmanModelCatalog() (HerdsmanCatalog, error) { return b.a.HerdsmanModelCatalog() }
func (b *ModelB) HerdsmanModelDownload(model string) (HerdsmanOpResult, error) { return b.a.HerdsmanModelDownload(model) }
func (b *ModelB) HerdsmanModelStart(model string) (HerdsmanOpResult, error) { return b.a.HerdsmanModelStart(model) }
func (b *ModelB) HerdsmanModelStats() (HerdsmanModelStats, error) { return b.a.HerdsmanModelStats() }
func (b *ModelB) HerdsmanModelStop(model string) (HerdsmanOpResult, error) { return b.a.HerdsmanModelStop(model) }
func (b *ModelB) HerdsmanModelUninstall(model string) (HerdsmanOpResult, error) { return b.a.HerdsmanModelUninstall(model) }
func (b *ModelB) HerdsmanOperations() (HerdsmanOperations, error) { return b.a.HerdsmanOperations() }
func (b *ModelB) HerdsmanProbe() herdsman.Probe { return b.a.HerdsmanProbe() }
func (b *ModelB) HerdsmanSecurityCheck() herdsman.LanExposure { return b.a.HerdsmanSecurityCheck() }
func (b *ModelB) SetFeatureModel(feature string, engineID string, modelName string) error { return b.a.SetFeatureModel(feature, engineID, modelName) }
func (b *ModelB) SetFeatureModelEnabled(feature string, enabled bool) error { return b.a.SetFeatureModelEnabled(feature, enabled) }
func (b *ModelB) SetOfficeLocal(enabled bool) error { return b.a.SetOfficeLocal(enabled) }
func (b *ModelB) SetSensitiveLocal(enabled bool) error { return b.a.SetSensitiveLocal(enabled) }
