// Code generated by scripts/gen_bindings; DO NOT EDIT.

package app

import (
	"github.com/gaea/gaea/internal/assistant"
	"github.com/gaea/gaea/internal/modelengine"
	"github.com/gaea/gaea/internal/whisper"
)

// VoiceB 语音（TTS/ASR/轻语）绑定门面（S2-3「App 绑定面拆分」）：仅暴露语音（TTS/ASR/轻语）的方法，
// 方法体零改动——纯委托给 App 实例（b.a.<Method>）。
type VoiceB struct{ a *App }

func (b *VoiceB) GetEngineList() []string { return b.a.GetEngineList() }
func (b *VoiceB) TTSSpeak(text string) (string, error) { return b.a.TTSSpeak(text) }
func (b *VoiceB) TTSSpeakBase64(text string) (map[string]interface{}, error) { return b.a.TTSSpeakBase64(text) }
func (b *VoiceB) TTSSpeakStreaming(text string) error { return b.a.TTSSpeakStreaming(text) }
func (b *VoiceB) VoiceApplySettings(settings map[string]interface{}) error { return b.a.VoiceApplySettings(settings) }
func (b *VoiceB) VoiceCancelTTS() error { return b.a.VoiceCancelTTS() }
func (b *VoiceB) VoiceChatText(text string) error { return b.a.VoiceChatText(text) }
func (b *VoiceB) VoiceGetSettings() map[string]interface{} { return b.a.VoiceGetSettings() }
func (b *VoiceB) VoiceGetState() map[string]interface{} { return b.a.VoiceGetState() }
func (b *VoiceB) VoiceHealth() map[string]interface{} { return b.a.VoiceHealth() }
func (b *VoiceB) VoicePlaybackDone() error { return b.a.VoicePlaybackDone() }
func (b *VoiceB) VoicePushAudio(chunk []byte) error { return b.a.VoicePushAudio(chunk) }
func (b *VoiceB) VoiceRestartService() error { return b.a.VoiceRestartService() }
func (b *VoiceB) VoiceSetInputChannel(channel string) error { return b.a.VoiceSetInputChannel(channel) }
func (b *VoiceB) VoiceSetMode(mode string) error { return b.a.VoiceSetMode(mode) }
func (b *VoiceB) VoiceSetPTTActive(active bool) error { return b.a.VoiceSetPTTActive(active) }
func (b *VoiceB) VoiceStart(browserASR bool) error { return b.a.VoiceStart(browserASR) }
func (b *VoiceB) VoiceStop() error { return b.a.VoiceStop() }
func (b *VoiceB) WhisperAssistantDelete(id string) error { return b.a.WhisperAssistantDelete(id) }
func (b *VoiceB) WhisperAssistantList() []assistant.Assistant { return b.a.WhisperAssistantList() }
func (b *VoiceB) WhisperAssistantSave(ast assistant.Assistant) error { return b.a.WhisperAssistantSave(ast) }
func (b *VoiceB) WhisperChat(userMsg string, personalityID string, thinking bool) (result map[string]interface{}, err error) { return b.a.WhisperChat(userMsg, personalityID, thinking) }
func (b *VoiceB) WhisperChatWithSearch(userMsg string, personalityID string, thinking bool, forceSearch bool) (map[string]interface{}, error) { return b.a.WhisperChatWithSearch(userMsg, personalityID, thinking, forceSearch) }
func (b *VoiceB) WhisperClearSession(personalityID string) error { return b.a.WhisperClearSession(personalityID) }
func (b *VoiceB) WhisperDeleteFact(personalityID string, factID string) error { return b.a.WhisperDeleteFact(personalityID, factID) }
func (b *VoiceB) WhisperGetConfig() map[string]interface{} { return b.a.WhisperGetConfig() }
func (b *VoiceB) WhisperGetEngine() string { return b.a.WhisperGetEngine() }
func (b *VoiceB) WhisperGetEngines() []modelengine.EngineConfig { return b.a.WhisperGetEngines() }
func (b *VoiceB) WhisperGetFacts(personalityID string) []map[string]interface{} { return b.a.WhisperGetFacts(personalityID) }
func (b *VoiceB) WhisperGetImageModel() string { return b.a.WhisperGetImageModel() }
func (b *VoiceB) WhisperGetModel() string { return b.a.WhisperGetModel() }
func (b *VoiceB) WhisperGetPersonalities() []whisper.PersonalityPreset { return b.a.WhisperGetPersonalities() }
func (b *VoiceB) WhisperGetState(personalityID string) map[string]interface{} { return b.a.WhisperGetState(personalityID) }
func (b *VoiceB) WhisperGetTraces(personalityID string) []whisper.TurnTrace { return b.a.WhisperGetTraces(personalityID) }
func (b *VoiceB) WhisperSetAdultMode(personalityID string, enabled bool) error { return b.a.WhisperSetAdultMode(personalityID, enabled) }
func (b *VoiceB) WhisperSetEngine(engineID string) error { return b.a.WhisperSetEngine(engineID) }
func (b *VoiceB) WhisperSetImageModel(modelName string) error { return b.a.WhisperSetImageModel(modelName) }
func (b *VoiceB) WhisperSetModel(engineID string, modelName string) error { return b.a.WhisperSetModel(engineID, modelName) }
func (b *VoiceB) WhisperTaskPlanResume() bool { return b.a.WhisperTaskPlanResume() }
func (b *VoiceB) WhisperTaskPlanStatus() map[string]interface{} { return b.a.WhisperTaskPlanStatus() }
func (b *VoiceB) WhisperUpdateFact(personalityID string, factID string, updates map[string]interface{}) error { return b.a.WhisperUpdateFact(personalityID, factID, updates) }
func (b *VoiceB) WhisperWebSearch(query string) (map[string]interface{}, error) { return b.a.WhisperWebSearch(query) }
func (b *VoiceB) WhisperWeixinGetQR() (map[string]interface{}, error) { return b.a.WhisperWeixinGetQR() }
func (b *VoiceB) WhisperWeixinQRStatus(qrcode string) (map[string]interface{}, error) { return b.a.WhisperWeixinQRStatus(qrcode) }
func (b *VoiceB) WhisperWeixinQRStatusWithCode(qrcode string, verifyCode string) (map[string]interface{}, error) { return b.a.WhisperWeixinQRStatusWithCode(qrcode, verifyCode) }
func (b *VoiceB) WhisperWeixinStatus() []map[string]interface{} { return b.a.WhisperWeixinStatus() }
