// Code generated by scripts/gen_bindings; DO NOT EDIT.

package app

import (
	"github.com/gaea/gaea/internal/gaea/pricefeed"
)

// CostB 成本库与价格源绑定门面（S2-3「App 绑定面拆分」）：仅暴露成本库与价格源的方法，
// 方法体零改动——纯委托给 App 实例（b.a.<Method>）。
type CostB struct{ a *App }

func (b *CostB) GaeaCostCategories() []CostCategoryView { return b.a.GaeaCostCategories() }
func (b *CostB) GaeaCostCategoryDelete(id int) error { return b.a.GaeaCostCategoryDelete(id) }
func (b *CostB) GaeaCostCategorySave(parentID int, name string, sort int, id int) (int, error) { return b.a.GaeaCostCategorySave(parentID, name, sort, id) }
func (b *CostB) GaeaCostDelete(name string) error { return b.a.GaeaCostDelete(name) }
func (b *CostB) GaeaCostGet(name string) *CostEntry { return b.a.GaeaCostGet(name) }
func (b *CostB) GaeaCostImportAIParse(path string) (CostImportPreview, error) { return b.a.GaeaCostImportAIParse(path) }
func (b *CostB) GaeaCostImportApply(rows []CostEntry) (int, error) { return b.a.GaeaCostImportApply(rows) }
func (b *CostB) GaeaCostImportPreview(path string) (CostImportPreview, error) { return b.a.GaeaCostImportPreview(path) }
func (b *CostB) GaeaCostList() []CostSummary { return b.a.GaeaCostList() }
func (b *CostB) GaeaCostSave(e CostEntry) error { return b.a.GaeaCostSave(e) }
func (b *CostB) GaeaCostSearch(query string, category string, status string) []CostSummary { return b.a.GaeaCostSearch(query, category, status) }
func (b *CostB) GaeaPriceFetch(id string) (pricefeed.FetchRecord, error) { return b.a.GaeaPriceFetch(id) }
func (b *CostB) GaeaPriceFetchAll() (int, string) { return b.a.GaeaPriceFetchAll() }
func (b *CostB) GaeaPriceFetchApply(fetchID string, titles []string) (int, error) { return b.a.GaeaPriceFetchApply(fetchID, titles) }
func (b *CostB) GaeaPriceFetchIgnore(fetchID string) error { return b.a.GaeaPriceFetchIgnore(fetchID) }
func (b *CostB) GaeaPriceFetches() []pricefeed.FetchRecord { return b.a.GaeaPriceFetches() }
func (b *CostB) GaeaPriceHistory(name string) []pricefeed.History { return b.a.GaeaPriceHistory(name) }
func (b *CostB) GaeaPriceSourceDelete(id string) error { return b.a.GaeaPriceSourceDelete(id) }
func (b *CostB) GaeaPriceSourceSave(src pricefeed.Source) error { return b.a.GaeaPriceSourceSave(src) }
func (b *CostB) GaeaPriceSources() []pricefeed.Source { return b.a.GaeaPriceSources() }
