// Code generated by scripts/gen_bindings; DO NOT EDIT.

package app

import (
	"github.com/gaea/gaea/internal/gaea/browser"
	"github.com/gaea/gaea/internal/gaea/contextview"
	"github.com/gaea/gaea/internal/gaea/event"
	"github.com/gaea/gaea/internal/gaea/evidence"
	"github.com/gaea/gaea/internal/office"
	"github.com/gaea/gaea/internal/office/standard"
	"github.com/gaea/gaea/internal/gaea/tasks"
	"github.com/gaea/gaea/internal/gaea/trajectory"
)

// OfficeB 办公引擎与工作区绑定门面（S2-3「App 绑定面拆分」）：仅暴露办公引擎与工作区的方法，
// 方法体零改动——纯委托给 App 实例（b.a.<Method>）。
type OfficeB struct{ a *App }

func (b *OfficeB) GaeaAcceptMemorySuggestion(candidate interface{}) (string, error) { return b.a.GaeaAcceptMemorySuggestion(candidate) }
func (b *OfficeB) GaeaAcceptMergeSuggestion(keep string, archive string) (string, error) { return b.a.GaeaAcceptMergeSuggestion(keep, archive) }
func (b *OfficeB) GaeaAcceptSkillSuggestion(candidate interface{}) (string, error) { return b.a.GaeaAcceptSkillSuggestion(candidate) }
func (b *OfficeB) GaeaAddMCPServer(input MCPServerInput) (int, error) { return b.a.GaeaAddMCPServer(input) }
func (b *OfficeB) GaeaAddPermissionRule(list string, rule string) error { return b.a.GaeaAddPermissionRule(list, rule) }
func (b *OfficeB) GaeaAgentNetwork() (trajectory.AgentNetwork, error) { return b.a.GaeaAgentNetwork() }
func (b *OfficeB) GaeaAnswer(id string, answers []event.AskAnswer) { b.a.GaeaAnswer(id, answers) }
func (b *OfficeB) GaeaApplyUpdate() error { return b.a.GaeaApplyUpdate() }
func (b *OfficeB) GaeaApprove(id string, decision string) { b.a.GaeaApprove(id, decision) }
func (b *OfficeB) GaeaArchiveSession(path string) error { return b.a.GaeaArchiveSession(path) }
func (b *OfficeB) GaeaAttachmentDataURL(path string) (string, error) { return b.a.GaeaAttachmentDataURL(path) }
func (b *OfficeB) GaeaBalance() BalanceInfo { return b.a.GaeaBalance() }
func (b *OfficeB) GaeaBenchmarkStreamProbe(model string) (StreamProbeResult, error) { return b.a.GaeaBenchmarkStreamProbe(model) }
func (b *OfficeB) GaeaBrowserObserve() browser.ObserveView { return b.a.GaeaBrowserObserve() }
func (b *OfficeB) GaeaCallTool(name string, argsJSON string) (string, error) { return b.a.GaeaCallTool(name, argsJSON) }
func (b *OfficeB) GaeaCancel() { b.a.GaeaCancel() }
func (b *OfficeB) GaeaCapabilities() CapabilitiesView { return b.a.GaeaCapabilities() }
func (b *OfficeB) GaeaCaptureScreen() (string, error) { return b.a.GaeaCaptureScreen() }
func (b *OfficeB) GaeaCaptureSkill(in SkillCaptureInput) (SkillCaptureResult, error) { return b.a.GaeaCaptureSkill(in) }
func (b *OfficeB) GaeaChangeFactType(name string, typ string) (string, error) { return b.a.GaeaChangeFactType(name, typ) }
func (b *OfficeB) GaeaCheckUpdate() (*UpdateInfo, error) { return b.a.GaeaCheckUpdate() }
func (b *OfficeB) GaeaCheckpoints() []CheckpointMeta { return b.a.GaeaCheckpoints() }
func (b *OfficeB) GaeaCommands() []CommandInfo { return b.a.GaeaCommands() }
func (b *OfficeB) GaeaContext() ContextInfo { return b.a.GaeaContext() }
func (b *OfficeB) GaeaContextNodeDetail(seq int64) (contextview.NodeDetail, error) { return b.a.GaeaContextNodeDetail(seq) }
func (b *OfficeB) GaeaContextView() (contextview.ContextTimeline, error) { return b.a.GaeaContextView() }
func (b *OfficeB) GaeaConvertToPdf(rel string) (ConvertPdfResult, error) { return b.a.GaeaConvertToPdf(rel) }
func (b *OfficeB) GaeaCrossEmbed(in CrossEmbedInput) (CrossEmbedResult, error) { return b.a.GaeaCrossEmbed(in) }
func (b *OfficeB) GaeaDataBackupCancel() error { return b.a.GaeaDataBackupCancel() }
func (b *OfficeB) GaeaDataBackupCreate(destDir string) (map[string]interface{}, error) { return b.a.GaeaDataBackupCreate(destDir) }
func (b *OfficeB) GaeaDataBackupInfo() map[string]interface{} { return b.a.GaeaDataBackupInfo() }
func (b *OfficeB) GaeaDataBackupPending() map[string]interface{} { return b.a.GaeaDataBackupPending() }
func (b *OfficeB) GaeaDataBackupRestore(zipPath string) (map[string]interface{}, error) { return b.a.GaeaDataBackupRestore(zipPath) }
func (b *OfficeB) GaeaDataBackupRestoreResult() map[string]interface{} { return b.a.GaeaDataBackupRestoreResult() }
func (b *OfficeB) GaeaDataBackupRollback() (bool, error) { return b.a.GaeaDataBackupRollback() }
func (b *OfficeB) GaeaDeleteProvider(name string) error { return b.a.GaeaDeleteProvider(name) }
func (b *OfficeB) GaeaDeleteSession(path string) error { return b.a.GaeaDeleteSession(path) }
func (b *OfficeB) GaeaDeliverableRegistry(sessionPath string) DeliverableRegistryView { return b.a.GaeaDeliverableRegistry(sessionPath) }
func (b *OfficeB) GaeaDocumentLint(rel string) (standard.LintReport, error) { return b.a.GaeaDocumentLint(rel) }
func (b *OfficeB) GaeaDocxAcceptChanges(rel string, accept bool) (PreviewResult, error) { return b.a.GaeaDocxAcceptChanges(rel, accept) }
func (b *OfficeB) GaeaDocxApplyEdit(rel string, selectedText string, replacement string) (PreviewResult, error) { return b.a.GaeaDocxApplyEdit(rel, selectedText, replacement) }
func (b *OfficeB) GaeaExportDeliverable(in ExportDeliverableInput) (ExportDeliverableResult, error) { return b.a.GaeaExportDeliverable(in) }
func (b *OfficeB) GaeaFactBase() FactBaseView { return b.a.GaeaFactBase() }
func (b *OfficeB) GaeaFactBaseClear() error { return b.a.GaeaFactBaseClear() }
func (b *OfficeB) GaeaFactBasePromote() (int, error) { return b.a.GaeaFactBasePromote() }
func (b *OfficeB) GaeaFileIndexRebuild() (*tasks.Task, error) { return b.a.GaeaFileIndexRebuild() }
func (b *OfficeB) GaeaFileSearch(query string, limit int) []FileSearchHit { return b.a.GaeaFileSearch(query, limit) }
func (b *OfficeB) GaeaFileSemanticSearch(query string, topN int) ([]FileSemanticHit, error) { return b.a.GaeaFileSemanticSearch(query, topN) }
func (b *OfficeB) GaeaForget(name string) error { return b.a.GaeaForget(name) }
func (b *OfficeB) GaeaFork(turn int) error { return b.a.GaeaFork(turn) }
func (b *OfficeB) GaeaGitCommit(message string) (string, error) { return b.a.GaeaGitCommit(message) }
func (b *OfficeB) GaeaGitDiff(path string, staged bool) (string, error) { return b.a.GaeaGitDiff(path, staged) }
func (b *OfficeB) GaeaGitDiscard(path string) error { return b.a.GaeaGitDiscard(path) }
func (b *OfficeB) GaeaGitLog(limit int) ([]GitCommitInfo, error) { return b.a.GaeaGitLog(limit) }
func (b *OfficeB) GaeaGitStage(paths []string) error { return b.a.GaeaGitStage(paths) }
func (b *OfficeB) GaeaGitStatus() GitStatus { return b.a.GaeaGitStatus() }
func (b *OfficeB) GaeaGitUnstage(paths []string) error { return b.a.GaeaGitUnstage(paths) }
func (b *OfficeB) GaeaHistory() []HistoryMessage { return b.a.GaeaHistory() }
func (b *OfficeB) GaeaInit() error { return b.a.GaeaInit() }
func (b *OfficeB) GaeaJobs() []JobView { return b.a.GaeaJobs() }
func (b *OfficeB) GaeaJournalList(limit int) []evidence.ChangeRecord { return b.a.GaeaJournalList(limit) }
func (b *OfficeB) GaeaListDir(rel string) ([]DirEntry, error) { return b.a.GaeaListDir(rel) }
func (b *OfficeB) GaeaListProjectSessions() []ProjectGroup { return b.a.GaeaListProjectSessions() }
func (b *OfficeB) GaeaListSessions() []SessionMeta { return b.a.GaeaListSessions() }
func (b *OfficeB) GaeaListWorkspaces() []WorkspaceView { return b.a.GaeaListWorkspaces() }
func (b *OfficeB) GaeaLogFrontendError(message string) { b.a.GaeaLogFrontendError(message) }
func (b *OfficeB) GaeaLoginProvider(name string) error { return b.a.GaeaLoginProvider(name) }
func (b *OfficeB) GaeaLogoutProvider(name string) error { return b.a.GaeaLogoutProvider(name) }
func (b *OfficeB) GaeaMaterials(limit int) []FileSearchHit { return b.a.GaeaMaterials(limit) }
func (b *OfficeB) GaeaMeta() Meta { return b.a.GaeaMeta() }
func (b *OfficeB) GaeaMorningPreload() bool { return b.a.GaeaMorningPreload() }
func (b *OfficeB) GaeaNewSession() error { return b.a.GaeaNewSession() }
func (b *OfficeB) GaeaOCRText(imagePath string) (string, error) { return b.a.GaeaOCRText(imagePath) }
func (b *OfficeB) GaeaOfficeEditText(selectedText string, instruction string) (map[string]interface{}, error) { return b.a.GaeaOfficeEditText(selectedText, instruction) }
func (b *OfficeB) GaeaOpenDownloadPage() error { return b.a.GaeaOpenDownloadPage() }
func (b *OfficeB) GaeaOpenWorkspacePath(rel string) error { return b.a.GaeaOpenWorkspacePath(rel) }
func (b *OfficeB) GaeaPermLevel() string { return b.a.GaeaPermLevel() }
func (b *OfficeB) GaeaPickDirectory() string { return b.a.GaeaPickDirectory() }
func (b *OfficeB) GaeaPickFiles() []FilePickResult { return b.a.GaeaPickFiles() }
func (b *OfficeB) GaeaPickWorkspace() string { return b.a.GaeaPickWorkspace() }
func (b *OfficeB) GaeaPinMaterial(rel string) []FileSearchHit { return b.a.GaeaPinMaterial(rel) }
func (b *OfficeB) GaeaPinSession(path string, pinned bool) error { return b.a.GaeaPinSession(path, pinned) }
func (b *OfficeB) GaeaPinnedMaterials() []FileSearchHit { return b.a.GaeaPinnedMaterials() }
func (b *OfficeB) GaeaPptxOutline(rel string) PptxOutlineView { return b.a.GaeaPptxOutline(rel) }
func (b *OfficeB) GaeaPreview(rel string) PreviewResult { return b.a.GaeaPreview(rel) }
func (b *OfficeB) GaeaPromoteSubagent(sessionPath string, ref string) (string, error) { return b.a.GaeaPromoteSubagent(sessionPath, ref) }
func (b *OfficeB) GaeaReadFile(rel string) FilePreview { return b.a.GaeaReadFile(rel) }
func (b *OfficeB) GaeaRecognizeImage(imagePath string, prompt string) (string, error) { return b.a.GaeaRecognizeImage(imagePath, prompt) }
func (b *OfficeB) GaeaReload() (GaeaReloadResult, error) { return b.a.GaeaReload() }
func (b *OfficeB) GaeaRemember(scope string, note string) (string, error) { return b.a.GaeaRemember(scope, note) }
func (b *OfficeB) GaeaRemoveMCPServer(name string) error { return b.a.GaeaRemoveMCPServer(name) }
func (b *OfficeB) GaeaRemovePermissionRule(list string, rule string) error { return b.a.GaeaRemovePermissionRule(list, rule) }
func (b *OfficeB) GaeaRenameSession(path string, title string) error { return b.a.GaeaRenameSession(path, title) }
func (b *OfficeB) GaeaResumeSession(path string) ([]HistoryMessage, error) { return b.a.GaeaResumeSession(path) }
func (b *OfficeB) GaeaResyncEvents(afterSeq int) GaeaResyncResult { return b.a.GaeaResyncEvents(afterSeq) }
func (b *OfficeB) GaeaRetrievalEvalRun() (RetrievalEvalReport, error) { return b.a.GaeaRetrievalEvalRun() }
func (b *OfficeB) GaeaRetryMCPServer(name string) error { return b.a.GaeaRetryMCPServer(name) }
func (b *OfficeB) GaeaRevealWorkspacePath(rel string) error { return b.a.GaeaRevealWorkspacePath(rel) }
func (b *OfficeB) GaeaRewind(turn int, scope string) error { return b.a.GaeaRewind(turn, scope) }
func (b *OfficeB) GaeaRollbackRecord(id string) error { return b.a.GaeaRollbackRecord(id) }
func (b *OfficeB) GaeaRouteIntent(text string, dryRun bool) IntentResult { return b.a.GaeaRouteIntent(text, dryRun) }
func (b *OfficeB) GaeaRunning() bool { return b.a.GaeaRunning() }
func (b *OfficeB) GaeaSaveAttachmentFile(fileName string, base64Data string) (string, error) { return b.a.GaeaSaveAttachmentFile(fileName, base64Data) }
func (b *OfficeB) GaeaSaveDoc(path string, body string) (string, error) { return b.a.GaeaSaveDoc(path, body) }
func (b *OfficeB) GaeaSavePastedImage(dataURL string) (string, error) { return b.a.GaeaSavePastedImage(dataURL) }
func (b *OfficeB) GaeaSaveProvider(p ProviderView) error { return b.a.GaeaSaveProvider(p) }
func (b *OfficeB) GaeaSaveSettings(view SettingsView) error { return b.a.GaeaSaveSettings(view) }
func (b *OfficeB) GaeaSaveWindowState(state map[string]interface{}) error { return b.a.GaeaSaveWindowState(state) }
func (b *OfficeB) GaeaSend(input string) { b.a.GaeaSend(input) }
func (b *OfficeB) GaeaSessionStats(path string) SessionStatsView { return b.a.GaeaSessionStats(path) }
func (b *OfficeB) GaeaSetAgentParams(temperature float64, maxSteps int, systemPrompt string) error { return b.a.GaeaSetAgentParams(temperature, maxSteps, systemPrompt) }
func (b *OfficeB) GaeaSetDefaultModel(ref string) error { return b.a.GaeaSetDefaultModel(ref) }
func (b *OfficeB) GaeaSetMCPServerEnabled(name string, enabled bool) error { return b.a.GaeaSetMCPServerEnabled(name, enabled) }
func (b *OfficeB) GaeaSetMemoryEnabled(enabled bool) error { return b.a.GaeaSetMemoryEnabled(enabled) }
func (b *OfficeB) GaeaSetMorningPreload(enabled bool) error { return b.a.GaeaSetMorningPreload(enabled) }
func (b *OfficeB) GaeaSetPermLevel(level string) error { return b.a.GaeaSetPermLevel(level) }
func (b *OfficeB) GaeaSetPermissionMode(mode string) error { return b.a.GaeaSetPermissionMode(mode) }
func (b *OfficeB) GaeaSetProviderKey(apiKeyEnv string, value string) error { return b.a.GaeaSetProviderKey(apiKeyEnv, value) }
func (b *OfficeB) GaeaSetSandbox(bash string, network bool, workspaceRoot string, allowWrite []string) error { return b.a.GaeaSetSandbox(bash, network, workspaceRoot, allowWrite) }
func (b *OfficeB) GaeaSetSubagentEffort(effort string) error { return b.a.GaeaSetSubagentEffort(effort) }
func (b *OfficeB) GaeaSetSubagentModelForSkill(skill string, ref string) error { return b.a.GaeaSetSubagentModelForSkill(skill, ref) }
func (b *OfficeB) GaeaSettings() SettingsView { return b.a.GaeaSettings() }
func (b *OfficeB) GaeaSkills() []map[string]interface{} { return b.a.GaeaSkills() }
func (b *OfficeB) GaeaSlashArgs(input string) SlashArgsResult { return b.a.GaeaSlashArgs(input) }
func (b *OfficeB) GaeaSteer(input string) { b.a.GaeaSteer(input) }
func (b *OfficeB) GaeaSubagentContextView(sessionPath string, ref string) (contextview.ContextTimeline, error) { return b.a.GaeaSubagentContextView(sessionPath, ref) }
func (b *OfficeB) GaeaSubagentFollowUp(sessionPath string, ref string, prompt string) (string, error) { return b.a.GaeaSubagentFollowUp(sessionPath, ref, prompt) }
func (b *OfficeB) GaeaSubagentRuns(sessionPath string) SubagentRunsView { return b.a.GaeaSubagentRuns(sessionPath) }
func (b *OfficeB) GaeaSubagentTranscript(sessionPath string, ref string) (SubagentTranscriptView, error) { return b.a.GaeaSubagentTranscript(sessionPath, ref) }
func (b *OfficeB) GaeaSummarizeFile(rel string, focus string) (GaeaSummaryResult, error) { return b.a.GaeaSummarizeFile(rel, focus) }
func (b *OfficeB) GaeaSummarizeFrom(turn int) error { return b.a.GaeaSummarizeFrom(turn) }
func (b *OfficeB) GaeaSummarizeUpTo(turn int) error { return b.a.GaeaSummarizeUpTo(turn) }
func (b *OfficeB) GaeaSwitchWorkspace(path string) string { return b.a.GaeaSwitchWorkspace(path) }
func (b *OfficeB) GaeaTCCAReport() string { return b.a.GaeaTCCAReport() }
func (b *OfficeB) GaeaTaskCancel(id string) error { return b.a.GaeaTaskCancel(id) }
func (b *OfficeB) GaeaTaskKill(id string) error { return b.a.GaeaTaskKill(id) }
func (b *OfficeB) GaeaTaskList(space ...string) []tasks.Task { return b.a.GaeaTaskList(space...) }
func (b *OfficeB) GaeaTaskOutput(id string) (TaskOutputView, error) { return b.a.GaeaTaskOutput(id) }
func (b *OfficeB) GaeaTaskRetry(id string) error { return b.a.GaeaTaskRetry(id) }
func (b *OfficeB) GaeaTaskTemplates() []TaskTemplate { return b.a.GaeaTaskTemplates() }
func (b *OfficeB) GaeaTools() []map[string]interface{} { return b.a.GaeaTools() }
func (b *OfficeB) GaeaTrajectory() (trajectory.Trajectory, error) { return b.a.GaeaTrajectory() }
func (b *OfficeB) GaeaUnarchiveSession(path string) (string, error) { return b.a.GaeaUnarchiveSession(path) }
func (b *OfficeB) GaeaUnifiedSearch(query string, topN int, scope ...string) (UnifiedSearchView, error) { return b.a.GaeaUnifiedSearch(query, topN, scope...) }
func (b *OfficeB) GaeaUnpinMaterial(rel string) []FileSearchHit { return b.a.GaeaUnpinMaterial(rel) }
func (b *OfficeB) GaeaUpdateFact(name string, body string) (string, error) { return b.a.GaeaUpdateFact(name, body) }
func (b *OfficeB) GaeaVerifyRecord(id string) (evidence.Verdict, error) { return b.a.GaeaVerifyRecord(id) }
func (b *OfficeB) GaeaVersion() string { return b.a.GaeaVersion() }
func (b *OfficeB) GaeaWorkspaceSearch(query string, limit int) []WorkspaceSearchHit { return b.a.GaeaWorkspaceSearch(query, limit) }
func (b *OfficeB) GaeaWriteFile(rel string, content string) error { return b.a.GaeaWriteFile(rel, content) }
func (b *OfficeB) GaeaXlsxApplyEdit(rel string, opsJSON string) (XlsxEditResult, error) { return b.a.GaeaXlsxApplyEdit(rel, opsJSON) }
func (b *OfficeB) GaeaXlsxChart(in XlsxChartInput) (XlsxChartResult, error) { return b.a.GaeaXlsxChart(in) }
func (b *OfficeB) GaeaXlsxColOps(rel string, sheet string, action string, ref string) (XlsxEditResult, error) { return b.a.GaeaXlsxColOps(rel, sheet, action, ref) }
func (b *OfficeB) GaeaXlsxPlanEdit(rel string, sheet string, instruction string, selection string) (XlsxPlanResult, error) { return b.a.GaeaXlsxPlanEdit(rel, sheet, instruction, selection) }
func (b *OfficeB) GaeaXlsxRecalc(rel string) (XlsxEditResult, error) { return b.a.GaeaXlsxRecalc(rel) }
func (b *OfficeB) GaeaXlsxRowOps(rel string, sheet string, action string, ref string) (XlsxEditResult, error) { return b.a.GaeaXlsxRowOps(rel, sheet, action, ref) }
func (b *OfficeB) GaeaXlsxSetCell(rel string, sheet string, ref string, value string) (XlsxEditResult, error) { return b.a.GaeaXlsxSetCell(rel, sheet, ref, value) }
func (b *OfficeB) GaeaZipDeliverables(paths []string) (ZipDeliverableResult, error) { return b.a.GaeaZipDeliverables(paths) }
func (b *OfficeB) LocalTranslate(req LocalTranslateRequest) (LocalTranslateResult, error) { return b.a.LocalTranslate(req) }
func (b *OfficeB) OfficeCancelJob(s string) { b.a.OfficeCancelJob(s) }
func (b *OfficeB) OfficeExecute(act string, path string, tgt string, q string, url string, content string) office.ExecResult { return b.a.OfficeExecute(act, path, tgt, q, url, content) }
func (b *OfficeB) OfficeGetJobState(s string) *office.AgentJobState { return b.a.OfficeGetJobState(s) }
func (b *OfficeB) OfficeGetMode(s string) bool { return b.a.OfficeGetMode(s) }
func (b *OfficeB) OfficeIsTask(text string) bool { return b.a.OfficeIsTask(text) }
func (b *OfficeB) OfficeListFolder(p string) office.ExecResult { return b.a.OfficeListFolder(p) }
func (b *OfficeB) OfficeReadFile(p string) office.ExecResult { return b.a.OfficeReadFile(p) }
func (b *OfficeB) OfficeSetMode(s string, e bool) { b.a.OfficeSetMode(s, e) }
