// Code generated by scripts/gen_bindings; DO NOT EDIT.

package app

import (
	"reflect"
	"sort"
	"testing"
)

// TestBindingsCompleteness S2-3 测试兜底：绑定门面集合的方法集必须与
// App（含嵌入子状态提升）的导出方法集完全一致——不多、不少、无遗漏。
func TestBindingsCompleteness(t *testing.T) {
	app := &App{}
	var want, got []string
	// *App 的完整方法集（含 core/writingState/mediaState/whisperState/officeState 提升）
	collectExported(reflect.TypeOf(app), &want)
	for _, bnd := range NewBindings(app) {
		collectExported(reflect.TypeOf(bnd), &got)
	}
	sort.Strings(want)
	sort.Strings(got)
	if len(want) != len(got) {
		t.Fatalf("绑定面不一致：App 导出 %d 个方法，门面共 %d 个", len(want), len(got))
	}
	for i := range want {
		if want[i] != got[i] {
			t.Fatalf("绑定面不一致：App[%d]=%s vs 门面[%d]=%s", i, want[i], i, got[i])
		}
	}
}

// collectExported 收集类型的导出方法名（指针类型方法集已含嵌入提升，勿 deref）。
func collectExported(t reflect.Type, out *[]string) {
	for i := 0; i < t.NumMethod(); i++ {
		m := t.Method(i)
		if m.PkgPath == "" {
			*out = append(*out, m.Name)
		}
	}
}
