// Code generated by scripts/gen_bindings; DO NOT EDIT.

package app

import (
	"github.com/gaea/gaea/internal/chat"
)

// SinB 原罪（闲庭·图文故事创作）绑定门面（S2-3「App 绑定面拆分」）：仅暴露原罪（闲庭·图文故事创作）的方法，
// 方法体零改动——纯委托给 App 实例（b.a.<Method>）。
type SinB struct{ a *App }

func (b *SinB) SinCancel(topicID string) error { return b.a.SinCancel(topicID) }
func (b *SinB) SinCastGet(topicID string) ([]string, error) { return b.a.SinCastGet(topicID) }
func (b *SinB) SinCastSet(topicID string, ids []string) ([]string, error) { return b.a.SinCastSet(topicID, ids) }
func (b *SinB) SinExportMarkdown(topicID string) (string, error) { return b.a.SinExportMarkdown(topicID) }
func (b *SinB) SinIllustrate(topicID string, messageID int64, cue string, prompt string, size string) (map[string]interface{}, error) { return b.a.SinIllustrate(topicID, messageID, cue, prompt, size) }
func (b *SinB) SinMessages(topicID string) ([]chat.Message, error) { return b.a.SinMessages(topicID) }
func (b *SinB) SinStream(topicID string, message string) (string, error) { return b.a.SinStream(topicID, message) }
func (b *SinB) SinTopicClear(id string) error { return b.a.SinTopicClear(id) }
func (b *SinB) SinTopicCreate(title string) (chat.Topic, error) { return b.a.SinTopicCreate(title) }
func (b *SinB) SinTopicDelete(id string) error { return b.a.SinTopicDelete(id) }
func (b *SinB) SinTopicRename(id string, title string) error { return b.a.SinTopicRename(id, title) }
func (b *SinB) SinTopicsList() ([]chat.Topic, error) { return b.a.SinTopicsList() }
