// Code generated by scripts/gen_bindings; DO NOT EDIT.

package app

// NewBindings 返回全部板块绑定门面（S2-3）：main.go 把这些对象传给
// wails Bind，替代原来的单一 App 对象。方法按板块拆分，逻辑零改动。
func NewBindings(a *App) []interface{} {
	if a == nil {
		return nil
	}
	return []interface{}{
		&CoreB{a: a},
		&OfficeB{a: a},
		&MemoryB{a: a},
		&CostB{a: a},
		&ModelB{a: a},
		&VoiceB{a: a},
		&ChatB{a: a},
		&NovelB{a: a},
		&ImageB{a: a},
		&CharlibB{a: a},
	}
}
