// Code generated by scripts/gen_bindings; DO NOT EDIT.

package app

// ImageB 绘梦与媒体绑定门面（S2-3「App 绑定面拆分」）：仅暴露绘梦与媒体的方法，
// 方法体零改动——纯委托给 App 实例（b.a.<Method>）。
type ImageB struct{ a *App }

func (b *ImageB) CancelImageGeneration() bool { return b.a.CancelImageGeneration() }
func (b *ImageB) ExtractCharacterHeatmap() (map[string]interface{}, error) { return b.a.ExtractCharacterHeatmap() }
func (b *ImageB) ExtractEmotionCurve() ([]map[string]interface{}, error) { return b.a.ExtractEmotionCurve() }
func (b *ImageB) ExtractTimeline() (map[string]interface{}, error) { return b.a.ExtractTimeline() }
func (b *ImageB) GenerateCharacterPortrait(charID string, model string) (string, error) { return b.a.GenerateCharacterPortrait(charID, model) }
func (b *ImageB) GenerateDefaultCanvas() (map[string]interface{}, error) { return b.a.GenerateDefaultCanvas() }
func (b *ImageB) GenerateDiagram(prompt string) (map[string]interface{}, error) { return b.a.GenerateDiagram(prompt) }
func (b *ImageB) GenerateFreeImage(prompt string, negative string, size string, style string, model string, seed int, n int, lora string) (map[string]interface{}, error) { return b.a.GenerateFreeImage(prompt, negative, size, style, model, seed, n, lora) }
func (b *ImageB) GenerateMedia(paramsJSON string) (map[string]interface{}, error) { return b.a.GenerateMedia(paramsJSON) }
func (b *ImageB) GetActiveASRModel() map[string]string { return b.a.GetActiveASRModel() }
func (b *ImageB) GetActiveTTSModel() map[string]string { return b.a.GetActiveTTSModel() }
func (b *ImageB) GetChatVoiceModel() map[string]string { return b.a.GetChatVoiceModel() }
func (b *ImageB) GetComfyUILoras() ([]string, error) { return b.a.GetComfyUILoras() }
func (b *ImageB) GetComfyUIStatus() map[string]interface{} { return b.a.GetComfyUIStatus() }
func (b *ImageB) GetComfyUITaskProgress() map[string]interface{} { return b.a.GetComfyUITaskProgress() }
func (b *ImageB) GetImageBackend() string { return b.a.GetImageBackend() }
func (b *ImageB) GetImageBackendConfig() map[string]interface{} { return b.a.GetImageBackendConfig() }
func (b *ImageB) GetImageBackendInfo() map[string]string { return b.a.GetImageBackendInfo() }
func (b *ImageB) GetPortraitConfig() map[string]string { return b.a.GetPortraitConfig() }
func (b *ImageB) GetSystemStats() map[string]interface{} { return b.a.GetSystemStats() }
func (b *ImageB) GetTTSConfig() map[string]interface{} { return b.a.GetTTSConfig() }
func (b *ImageB) GetTTSSpeakers(model string) ([]string, error) { return b.a.GetTTSSpeakers(model) }
func (b *ImageB) GetTTSStatus() map[string]interface{} { return b.a.GetTTSStatus() }
func (b *ImageB) GetVoicePipelineConfig() map[string]interface{} { return b.a.GetVoicePipelineConfig() }
func (b *ImageB) ImageHubAssets(space string, sourceBoard string, limit int) []imageHubAssetView { return b.a.ImageHubAssets(space, sourceBoard, limit) }
func (b *ImageB) OpenImageSaveDir() error { return b.a.OpenImageSaveDir() }
func (b *ImageB) OpenNovelImagesDir() error { return b.a.OpenNovelImagesDir() }
func (b *ImageB) SaveTTSConfig(modelPath string, serverPath string, port int, backend string, speed float64) error { return b.a.SaveTTSConfig(modelPath, serverPath, port, backend, speed) }
func (b *ImageB) SetActiveASRModel(engineID string, modelID string) error { return b.a.SetActiveASRModel(engineID, modelID) }
func (b *ImageB) SetActiveTTSModel(engineID string, modelID string) error { return b.a.SetActiveTTSModel(engineID, modelID) }
func (b *ImageB) SetCharacterPortrait(charID string, imageData string) error { return b.a.SetCharacterPortrait(charID, imageData) }
func (b *ImageB) SetChatVoiceModel(engineID string, modelID string) error { return b.a.SetChatVoiceModel(engineID, modelID) }
func (b *ImageB) SetImageBackend(backend string, comfyUIURL string, imageModel string, imageSaveDir string) error { return b.a.SetImageBackend(backend, comfyUIURL, imageModel, imageSaveDir) }
func (b *ImageB) SetPortraitConfig(backend string, model string) error { return b.a.SetPortraitConfig(backend, model) }
func (b *ImageB) StartComfyUI() error { return b.a.StartComfyUI() }
func (b *ImageB) StartLocalTTSService(engineID string) map[string]interface{} { return b.a.StartLocalTTSService(engineID) }
func (b *ImageB) StartTTSServer(modelPath string, port int, backend string) error { return b.a.StartTTSServer(modelPath, port, backend) }
func (b *ImageB) StopComfyUI() error { return b.a.StopComfyUI() }
func (b *ImageB) StopTTSServer() error { return b.a.StopTTSServer() }
