// Code generated by scripts/gen_bindings -legacy-ts; DO NOT EDIT.
//
// legacy 绑定面清单：Go 导出绑定中不经 AppBindings 门面消费的名字（前端经
// wailsjsCompat / window.go 直调）。算法：-names 的 Go 全集减去
// spaceBindings.ts 的 facets 键（=AppBindings 键，satisfies 编译期钉死）经
// bridge/mappings.ts gaeaToGaea 映射后的认领集。与 bindingNames.ts（-names
// 模式）配套再生，两处计数随每次实测重写：
//
//	go run ./scripts/gen_bindings -legacy-ts
//
// 消费方：frontend/src/gaea/lib/bridge/drift.ts——LegacySurfaceNames 类型派生 +
// 「不过期/不重叠」两把编译期锁（手改、漏再生、与 AppBindings 认领重叠都会红）。
//
// 共 75 名 = Go 导出 654 − 认领且 Go 存在 579（facets 键 580，其中 mock-only 名无 Go 绑定不计）。

export const legacyBindings = [
  "AddCustomEngine",
  "ApplyBranch",
  "BrainSearch",
  "Chat",
  "ChatGeneral",
  "CmdKEdit",
  "CreateProject",
  "DeleteProject",
  "GaeaBenchmarkDetail",
  "GaeaBenchmarkExport",
  "GaeaBenchmarkList",
  "GaeaBenchmarkStart",
  "GaeaBenchmarkStreamProbe",
  "GaeaGetUsdCnyRate",
  "GaeaSetUsdCnyRate",
  "GaeaUsageOverview",
  "GetActiveEngine",
  "GetActiveOCRModel",
  "GetDeepseekKeyStatus",
  "GetEngineFailover",
  "GetEngines",
  "GetGlmKeyStatus",
  "GetLoginStatus",
  "GetModelCallStats",
  "GetModelHubKeyStatus", // Model Hub（Unsloth 本地引擎）Key 状态（引擎管理经 App() 直调）
  "GetModelMonitor",
  "GetModelRoute",
  "GetNovelsDir",
  "GetOfficeLocal",
  "GetOfflineMode",
  "GetOpencodeGoKeyStatus",
  "GetOpencodeZenKeyStatus",
  "GetOutlines",
  "GetProjectInfo",
  "GetSensitiveLocal",
  "HerdsmanLaunchPresets",
  "HerdsmanModelCatalog",
  "HerdsmanModelDownload",
  "HerdsmanModelStart",
  "HerdsmanModelStats",
  "HerdsmanModelStop",
  "HerdsmanModelUninstall",
  "HerdsmanSecurityCheck",
  "ImportNovelBook",
  "IsProjectV4",
  "Login",
  "Logout",
  "NovelGhostSuggest", // v4.444 场景编辑器内联续写（GhostText；wailsApp 直调 legacy 面）
  "OpenProject",
  "RefreshEngineModels",
  "RemoveCustomEngine",
  "ReorderScenes",
  "ResetModelCallStats",
  "RunChapterGate", // 章节闸门（v4.7x 小说革命遗留：场景级生成/叙事状态结算族已随批次三b 迁 AppBindings，仅此仍 wailsjsCompat 直调）
  "SaveEngine",
  "SaveScene",
  "Search",
  "SetActiveEngine",
  "SetActiveOCRModel",
  "SetDeepseekKey",
  "SetEngineDefaultModel",
  "SetEngineFailover",
  "SetGlmEndpoint",
  "SetGlmKey",
  "SetModelHubKey", // Model Hub（Unsloth 本地引擎）Key（Unsloth 设置 → API 创建）
  "SetOfficeLocal",
  "SetOfflineMode",
  "SetOpencodeGoKey",
  "SetOpencodeZenKey",
  "SetSensitiveLocal",
  "StartModelHubModel", // Model Hub：让 Unsloth Studio 加载/切换模型（ollama-manifest 引用）
  "TTSSpeakStreaming",
  "TestEngineConnection",
  "UpdateCustomEngine",
  "UpdateProjectMeta", // v4.439 项目元信息更新（小说创作间本书定位；wailsApp 直调 legacy 面）
] as const;
