// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {app} from '../models';
import {event} from '../models';
import {modelengine} from '../models';
import {office} from '../models';
import {search} from '../models';
import {fs} from '../models';
import {assistant} from '../models';
import {whisper} from '../models';

export function AddOutlineNode(arg1:string):Promise<void>;

export function AnalyzeChapter(arg1:number):Promise<Record<string, any>>;

export function AnalyzeStyle():Promise<Record<string, any>>;

export function ApplyBranch(arg1:string,arg2:number,arg3:string):Promise<Record<string, any>>;

export function BrainstormBranches(arg1:string):Promise<Record<string, any>>;

export function BuildBacklinkIndex():Promise<Record<string, any>>;

export function BuildContextBudget(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<Record<string, any>>;

export function BuildRichContext(arg1:string,arg2:string):Promise<Record<string, any>>;

export function Chat(arg1:string,arg2:string):Promise<string>;

export function ChatCharacter(arg1:string):Promise<Record<string, any>>;

export function ChatCharacterDetail(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ChatGeneral(arg1:string):Promise<Record<string, any>>;

export function ChatOutline(arg1:string):Promise<Record<string, any>>;

export function ChatOutlineNode(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ChatWorldview(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CheckConsistency():Promise<Record<string, any>>;

export function CloseProject():Promise<void>;

export function CmdKEdit(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ContinueOutline(arg1:number):Promise<Record<string, any>>;

export function CreateChapter(arg1:string,arg2:string,arg3:string,arg4:number,arg5:string,arg6:string):Promise<Record<string, any>>;

export function CreateProject(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function CreateSnapshot(arg1:string,arg2:number,arg3:string):Promise<Record<string, any>>;

export function DeleteCharacter(arg1:string):Promise<void>;

export function DeleteLorebookEntry(arg1:string):Promise<void>;

export function DeleteOrganization(arg1:string):Promise<void>;

export function DeleteOutlineNode(arg1:string):Promise<void>;

export function DeleteProject(arg1:string):Promise<void>;

export function DeleteRelationship(arg1:string,arg2:string):Promise<void>;

export function ExpandOutlineNode(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ExportAll():Promise<Record<string, string>>;

export function ExportHTML(arg1:string):Promise<Record<string, any>>;

export function ExtractCharacterHeatmap():Promise<Record<string, any>>;

export function ExtractEmotionCurve():Promise<Array<Record<string, any>>>;

export function ExtractTimeline():Promise<Record<string, any>>;

export function FindLorebookTriggers(arg1:string):Promise<Array<Record<string, any>>>;

export function FindUnlinkedMentions(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function GaeaAcceptMemorySuggestion(arg1:any):Promise<string>;

export function GaeaAcceptSkillSuggestion(arg1:any):Promise<string>;

export function GaeaAddMCPServer(arg1:app.MCPServerInput):Promise<number>;

export function GaeaAddPermissionRule(arg1:string,arg2:string):Promise<void>;

export function GaeaAgentMode():Promise<string>;

export function GaeaAnswer(arg1:string,arg2:Array<event.AskAnswer>):Promise<void>;

export function GaeaApplyUpdate():Promise<void>;

export function GaeaApprove(arg1:string,arg2:boolean,arg3:boolean):Promise<void>;

export function GaeaAttachmentDataURL(arg1:string):Promise<string>;

export function GaeaBalance():Promise<app.BalanceInfo>;

export function GaeaCallTool(arg1:string,arg2:string):Promise<string>;

export function GaeaCancel():Promise<void>;

export function GaeaCapabilities():Promise<app.CapabilitiesView>;

export function GaeaChangeFactType(arg1:string,arg2:string):Promise<string>;

export function GaeaCheckUpdate():Promise<app.UpdateInfo>;

export function GaeaCheckpoints():Promise<Array<app.CheckpointMeta>>;

export function GaeaCommands():Promise<Array<app.CommandInfo>>;

export function GaeaContext():Promise<app.ContextInfo>;

export function GaeaCostDelete(arg1:string):Promise<void>;

export function GaeaCostGet(arg1:string):Promise<app.CostEntry>;

export function GaeaCostList():Promise<Array<app.CostSummary>>;

export function GaeaCostSave(arg1:app.CostEntry):Promise<void>;

export function GaeaCostSearch(arg1:string,arg2:string,arg3:string):Promise<Array<app.CostSummary>>;

export function GaeaDeleteProvider(arg1:string):Promise<void>;

export function GaeaDeleteSession(arg1:string):Promise<void>;

export function GaeaEngines():Promise<Array<modelengine.EngineConfig>>;

export function GaeaForget(arg1:string):Promise<void>;

export function GaeaFork(arg1:number):Promise<void>;

export function GaeaHistory():Promise<Array<app.HistoryMessage>>;

export function GaeaInit():Promise<void>;

export function GaeaJobs():Promise<Array<app.JobView>>;

export function GaeaKnowledgeDelete(arg1:string):Promise<void>;

export function GaeaKnowledgeGet(arg1:string):Promise<app.KnowledgeEntry>;

export function GaeaKnowledgeList():Promise<Array<app.KnowledgeSummary>>;

export function GaeaKnowledgeSave(arg1:app.KnowledgeEntry):Promise<void>;

export function GaeaKnowledgeSearch(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<app.KnowledgeSummary>>;

export function GaeaListDir(arg1:string):Promise<Array<app.DirEntry>>;

export function GaeaListSessions():Promise<Array<app.SessionMeta>>;

export function GaeaListWorkspaces():Promise<Array<app.WorkspaceView>>;

export function GaeaLoginProvider(arg1:string):Promise<void>;

export function GaeaLogoutProvider(arg1:string):Promise<void>;

export function GaeaMemory():Promise<app.MemoryView>;

export function GaeaMemoryGraph():Promise<app.MemoryGraphView>;

export function GaeaMemoryHubOverview():Promise<app.MemoryHubOverview>;

export function GaeaMemorySuggestions():Promise<app.MemorySuggestionsView>;

export function GaeaMeta():Promise<app.Meta>;

export function GaeaModel():Promise<string>;

export function GaeaModels():Promise<Array<app.ModelInfo>>;

export function GaeaNewSession():Promise<void>;

export function GaeaOpenDownloadPage():Promise<void>;

export function GaeaOpenWorkspacePath(arg1:string):Promise<void>;

export function GaeaPermLevel():Promise<string>;

export function GaeaPickDirectory():Promise<string>;

export function GaeaPickFiles():Promise<Array<app.FilePickResult>>;

export function GaeaPickWorkspace():Promise<string>;

export function GaeaProfileConflicts():Promise<Array<string>>;

export function GaeaProfileDelete(arg1:string):Promise<void>;

export function GaeaProfileList():Promise<Array<app.ProfileFactView>>;

export function GaeaProfileResolveConflict(arg1:string,arg2:string):Promise<void>;

export function GaeaProfileSave(arg1:app.ProfileFactView):Promise<void>;

export function GaeaReadFile(arg1:string):Promise<app.FilePreview>;

export function GaeaRemember(arg1:string,arg2:string):Promise<string>;

export function GaeaRemoveMCPServer(arg1:string):Promise<void>;

export function GaeaRemovePermissionRule(arg1:string,arg2:string):Promise<void>;

export function GaeaRenameSession(arg1:string,arg2:string):Promise<void>;

export function GaeaResumeSession(arg1:string):Promise<Array<app.HistoryMessage>>;

export function GaeaRetryMCPServer(arg1:string):Promise<void>;

export function GaeaRevealWorkspacePath(arg1:string):Promise<void>;

export function GaeaRewind(arg1:number,arg2:string):Promise<void>;

export function GaeaRunning():Promise<boolean>;

export function GaeaSaveAttachmentFile(arg1:string,arg2:string):Promise<string>;

export function GaeaSaveDoc(arg1:string,arg2:string):Promise<string>;

export function GaeaSavePastedImage(arg1:string):Promise<string>;

export function GaeaSaveProvider(arg1:app.ProviderView):Promise<void>;

export function GaeaSaveSettings(arg1:app.SettingsView):Promise<void>;

export function GaeaSaveWindowState(arg1:Record<string, any>):Promise<void>;

export function GaeaSelectTab(arg1:string):Promise<void>;

export function GaeaSend(arg1:string):Promise<void>;

export function GaeaSetAgentParams(arg1:number,arg2:number,arg3:string):Promise<void>;

export function GaeaSetDefaultModel(arg1:string):Promise<void>;

export function GaeaSetEngine(arg1:string):Promise<void>;

export function GaeaSetMCPServerEnabled(arg1:string,arg2:boolean):Promise<void>;

export function GaeaSetModel(arg1:string):Promise<void>;

export function GaeaSetPermLevel(arg1:string):Promise<void>;

export function GaeaSetPermissionMode(arg1:string):Promise<void>;

export function GaeaSetProviderKey(arg1:string,arg2:string):Promise<void>;

export function GaeaSetSandbox(arg1:string,arg2:boolean,arg3:string,arg4:Array<string>):Promise<void>;

export function GaeaSetSubagentEffort(arg1:string):Promise<void>;

export function GaeaSetSubagentModelForSkill(arg1:string,arg2:string):Promise<void>;

export function GaeaSettings():Promise<app.SettingsView>;

export function GaeaSkills():Promise<Array<Record<string, any>>>;

export function GaeaSlashArgs(arg1:string):Promise<app.SlashArgsResult>;

export function GaeaSummarizeFrom(arg1:number):Promise<void>;

export function GaeaSummarizeUpTo(arg1:number):Promise<void>;

export function GaeaSwitchWorkspace(arg1:string):Promise<string>;

export function GaeaTCCAReport():Promise<string>;

export function GaeaTabMeta():Promise<Array<app.TabMeta>>;

export function GaeaTools():Promise<Array<Record<string, any>>>;

export function GaeaUpdateFact(arg1:string,arg2:string):Promise<string>;

export function GaeaVersion():Promise<string>;

export function GaeaWhisperEpisodes():Promise<Array<app.WhisperEpisodeView>>;

export function GaeaWhisperExportArchive(arg1:string):Promise<number>;

export function GaeaWhisperMemories():Promise<Array<app.WhisperMemoryView>>;

export function GaeaWorkspaceChanges():Promise<Array<app.WorkspaceChangeView>>;

export function GenerateCharacterPortrait(arg1:string,arg2:string):Promise<string>;

export function GenerateCharacters(arg1:number):Promise<Record<string, any>>;

export function GenerateDefaultCanvas():Promise<Record<string, any>>;

export function GenerateFreeImage(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number,arg7:number,arg8:string):Promise<Record<string, any>>;

export function GenerateOutlineWithDialogue(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function GenerateSceneIllustration(arg1:number):Promise<Record<string, any>>;

export function GenerateSingleCharacter(arg1:string):Promise<Record<string, any>>;

export function GetActiveASRModel():Promise<Record<string, string>>;

export function GetActiveEngine():Promise<string>;

export function GetActiveModel():Promise<string>;

export function GetActiveTTSModel():Promise<Record<string, string>>;

export function GetAllEntityNames():Promise<Array<Record<string, any>>>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetBacklinks(arg1:string):Promise<Array<Record<string, any>>>;

export function GetBookData():Promise<Record<string, any>>;

export function GetChapter(arg1:number):Promise<Record<string, any>>;

export function GetChapterBranch(arg1:number,arg2:string):Promise<Record<string, any>>;

export function GetChapterScenes(arg1:number):Promise<Array<Record<string, any>>>;

export function GetCharacters():Promise<Record<string, any>>;

export function GetComfyUILoras():Promise<Array<string>>;

export function GetComfyUIStatus():Promise<Record<string, any>>;

export function GetCompileTemplates():Promise<Array<Record<string, any>>>;

export function GetConfig():Promise<Record<string, string>>;

export function GetDashboard(arg1:number):Promise<Record<string, any>>;

export function GetDeepseekKeyStatus():Promise<Record<string, any>>;

export function GetEngineList():Promise<Array<string>>;

export function GetEngines():Promise<Array<modelengine.EngineConfig>>;

export function GetEntityRelations():Promise<Record<string, any>>;

export function GetFeatureModel(arg1:string):Promise<Record<string, string>>;

export function GetForeshadows():Promise<Record<string, any>>;

export function GetImageBackend():Promise<string>;

export function GetImageBackendConfig():Promise<Record<string, any>>;

export function GetImageBackendInfo():Promise<Record<string, string>>;

export function GetLoginStatus():Promise<boolean>;

export function GetLorebookEntries():Promise<Record<string, any>>;

export function GetModelMonitor():Promise<Record<string, any>>;

export function GetNovelsDir():Promise<string>;

export function GetOutlines():Promise<Record<string, any>>;

export function GetProjectInfo():Promise<Record<string, any>>;

export function GetStats():Promise<Record<string, any>>;

export function GetStyleProfile():Promise<Record<string, any>>;

export function GetSystemStats():Promise<Record<string, any>>;

export function GetTTSConfig():Promise<Record<string, any>>;

export function GetTTSStatus():Promise<Record<string, any>>;

export function GetVoicePipelineConfig():Promise<Record<string, any>>;

export function GetWorldMapImage():Promise<string>;

export function GetWorldview():Promise<string>;

export function GetWorldviewSections():Promise<Record<string, any>>;

export function ImportStyleProfile(arg1:string,arg2:string):Promise<Record<string, any>>;

export function InjectMemories(arg1:string,arg2:number,arg3:number):Promise<Record<string, any>>;

export function IsProjectV4():Promise<boolean>;

export function ListProjects():Promise<Array<app.ProjectCard>>;

export function ListSkills():Promise<Array<Record<string, any>>>;

export function ListSnapshots(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function Login():Promise<void>;

export function Logout():Promise<void>;

export function MigrateProjectToV4():Promise<void>;

export function OfficeCancelJob(arg1:string):Promise<void>;

export function OfficeExecute(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<office.ExecResult>;

export function OfficeGetJobState(arg1:string):Promise<office.AgentJobState>;

export function OfficeGetMode(arg1:string):Promise<boolean>;

export function OfficeIsTask(arg1:string):Promise<boolean>;

export function OfficeListFolder(arg1:string):Promise<office.ExecResult>;

export function OfficeReadFile(arg1:string):Promise<office.ExecResult>;

export function OfficeSetMode(arg1:string,arg2:boolean):Promise<void>;

export function OpenImageSaveDir():Promise<void>;

export function OpenNovelImagesDir():Promise<void>;

export function OpenProject(arg1:string):Promise<Record<string, any>>;

export function ParseLinks(arg1:string):Promise<Array<string>>;

export function ProposalAddSection(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ProposalCheckCompliance(arg1:string):Promise<Record<string, any>>;

export function ProposalCheckCoverage(arg1:string):Promise<Record<string, any>>;

export function ProposalConvertFiles(arg1:string):Promise<void>;

export function ProposalCreate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<Record<string, any>>;

export function ProposalDelete(arg1:string):Promise<void>;

export function ProposalExport(arg1:string):Promise<string>;

export function ProposalExportDocx(arg1:string):Promise<string>;

export function ProposalGenerateChart(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ProposalGenerateOutline(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ProposalGenerateSection(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ProposalGenerateSectionStream(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ProposalGet(arg1:string):Promise<Record<string, any>>;

export function ProposalList():Promise<Array<Record<string, any>>>;

export function ProposalParseBidFile(arg1:string):Promise<Record<string, any>>;

export function ProposalPolish(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Record<string, any>>;

export function ProposalProjectCreate(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ProposalProjectDelete(arg1:string):Promise<void>;

export function ProposalProjectList():Promise<Array<Record<string, any>>>;

export function ProposalReadFile(arg1:string):Promise<string>;

export function ProposalRemoveRawFile(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ProposalRemoveSection(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ProposalRenameSection(arg1:string,arg2:string,arg3:string):Promise<Record<string, any>>;

export function ProposalSaveRawText(arg1:string,arg2:string):Promise<Record<string, any>>;

export function ProposalSaveUploadedFile(arg1:string,arg2:string,arg3:Array<number>):Promise<Record<string, any>>;

export function ProposalTemplates():Promise<Array<Record<string, any>>>;

export function ProposalUpdate(arg1:Record<string, any>):Promise<void>;

export function QueryEntities(arg1:string):Promise<Array<Record<string, any>>>;

export function QuickBrainstormBranches(arg1:string,arg2:string):Promise<Record<string, any>>;

export function RefreshEngineModels(arg1:string):Promise<Array<modelengine.ModelInfo>>;

export function ReorderScenes(arg1:number,arg2:Array<string>):Promise<void>;

export function RestoreSnapshot(arg1:string,arg2:string,arg3:number):Promise<void>;

export function ReviewBook():Promise<Record<string, any>>;

export function SaveAllWorldviewSections(arg1:string):Promise<void>;

export function SaveChapterBranchContent(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SaveChapterContent(arg1:number,arg2:string):Promise<void>;

export function SaveCharacter(arg1:string):Promise<void>;

export function SaveCharacters(arg1:string):Promise<void>;

export function SaveCharactersBatch(arg1:string):Promise<Record<string, any>>;

export function SaveConfig(arg1:string,arg2:string):Promise<void>;

export function SaveEngine(arg1:modelengine.EngineConfig):Promise<void>;

export function SaveLorebookEntry(arg1:string):Promise<void>;

export function SaveOrganization(arg1:string):Promise<void>;

export function SaveOutlineNode(arg1:string):Promise<void>;

export function SaveRelationship(arg1:string):Promise<void>;

export function SaveScene(arg1:number,arg2:string,arg3:string):Promise<void>;

export function SaveTTSConfig(arg1:string,arg2:string,arg3:number,arg4:string,arg5:number):Promise<void>;

export function SaveToken(arg1:string):Promise<void>;

export function SaveWorldMapImage(arg1:string):Promise<void>;

export function SaveWorldview(arg1:string):Promise<void>;

export function SaveWorldviewSection(arg1:string,arg2:string):Promise<void>;

export function Search(arg1:string):Promise<Record<string, Array<search.Result>>>;

export function SearchMemories(arg1:string,arg2:number):Promise<Array<Record<string, any>>>;

export function SetActiveASRModel(arg1:string,arg2:string):Promise<void>;

export function SetActiveEngine(arg1:string):Promise<void>;

export function SetActiveTTSModel(arg1:string,arg2:string):Promise<void>;

export function SetCharacterPortrait(arg1:string,arg2:string):Promise<void>;

export function SetDeepseekKey(arg1:string):Promise<void>;

export function SetDistFS(arg1:fs.FS):Promise<void>;

export function SetEngineDefaultModel(arg1:string,arg2:string):Promise<void>;

export function SetFeatureModel(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetImageBackend(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function StartComfyUI():Promise<void>;

export function StartTTSServer(arg1:string,arg2:number,arg3:string):Promise<void>;

export function StopComfyUI():Promise<void>;

export function StopTTSServer():Promise<void>;

export function SyncEntityDB():Promise<Record<string, any>>;

export function TTSSpeak(arg1:string):Promise<string>;

export function TTSSpeakBase64(arg1:string):Promise<Record<string, any>>;

export function TTSSpeakStreaming(arg1:string):Promise<void>;

export function TestEngineConnection(arg1:string):Promise<modelengine.EngineStatus>;

export function ToggleOrgMember(arg1:string,arg2:string):Promise<void>;

export function VoiceApplySettings(arg1:Record<string, any>):Promise<void>;

export function VoiceCancelTTS():Promise<void>;

export function VoiceGetSettings():Promise<Record<string, any>>;

export function VoiceGetState():Promise<Record<string, any>>;

export function VoiceHealth():Promise<Record<string, any>>;

export function VoicePushAudio(arg1:Array<number>):Promise<void>;

export function VoiceRestartService():Promise<void>;

export function VoiceSetInputChannel(arg1:string):Promise<void>;

export function VoiceSetMode(arg1:string):Promise<void>;

export function VoiceSetPTTActive(arg1:boolean):Promise<void>;

export function VoiceStart():Promise<void>;

export function VoiceStop():Promise<void>;

export function WhisperAssistantDelete(arg1:string):Promise<void>;

export function WhisperAssistantList():Promise<Array<assistant.Assistant>>;

export function WhisperAssistantSave(arg1:assistant.Assistant):Promise<void>;

export function WhisperChat(arg1:string,arg2:string):Promise<Record<string, any>>;

export function WhisperChatWithSearch(arg1:string,arg2:string):Promise<Record<string, any>>;

export function WhisperClearSession(arg1:string):Promise<void>;

export function WhisperDeleteFact(arg1:string,arg2:string):Promise<void>;

export function WhisperGetConfig():Promise<Record<string, any>>;

export function WhisperGetEngine():Promise<string>;

export function WhisperGetEngines():Promise<Array<modelengine.EngineConfig>>;

export function WhisperGetFacts(arg1:string):Promise<Array<Record<string, any>>>;

export function WhisperGetImageModel():Promise<string>;

export function WhisperGetModel():Promise<string>;

export function WhisperGetPersonalities():Promise<Array<whisper.PersonalityPreset>>;

export function WhisperGetState(arg1:string):Promise<Record<string, any>>;

export function WhisperSetAdultMode(arg1:string,arg2:boolean):Promise<void>;

export function WhisperSetEngine(arg1:string):Promise<void>;

export function WhisperSetImageModel(arg1:string):Promise<void>;

export function WhisperSetModel(arg1:string,arg2:string):Promise<void>;

export function WhisperUpdateFact(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function WhisperWebSearch(arg1:string):Promise<Record<string, any>>;

export function WhisperWeixinGetQR():Promise<Record<string, any>>;

export function WhisperWeixinQRStatus(arg1:string):Promise<Record<string, any>>;

export function WhisperWeixinQRStatusWithCode(arg1:string,arg2:string):Promise<Record<string, any>>;

export function WhisperWeixinStatus():Promise<Array<Record<string, any>>>;
