// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddOutlineNode(arg1) {
  return window['go']['app']['App']['AddOutlineNode'](arg1);
}

export function AnalyzeChapter(arg1) {
  return window['go']['app']['App']['AnalyzeChapter'](arg1);
}

export function AnalyzeStyle() {
  return window['go']['app']['App']['AnalyzeStyle']();
}

export function ApplyBranch(arg1, arg2, arg3) {
  return window['go']['app']['App']['ApplyBranch'](arg1, arg2, arg3);
}

export function BrainCrossRefs(arg1) {
  return window['go']['app']['App']['BrainCrossRefs'](arg1);
}

export function BrainSearch(arg1, arg2) {
  return window['go']['app']['App']['BrainSearch'](arg1, arg2);
}

export function BrainWrite(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['BrainWrite'](arg1, arg2, arg3, arg4);
}

export function BrainstormBranches(arg1) {
  return window['go']['app']['App']['BrainstormBranches'](arg1);
}

export function BuildBacklinkIndex() {
  return window['go']['app']['App']['BuildBacklinkIndex']();
}

export function BuildContextBudget(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['BuildContextBudget'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function BuildRichContext(arg1, arg2) {
  return window['go']['app']['App']['BuildRichContext'](arg1, arg2);
}

export function CharacterAssociate(arg1, arg2) {
  return window['go']['app']['App']['CharacterAssociate'](arg1, arg2);
}

export function CharacterDelete(arg1) {
  return window['go']['app']['App']['CharacterDelete'](arg1);
}

export function CharacterDissociate(arg1) {
  return window['go']['app']['App']['CharacterDissociate'](arg1);
}

export function CharacterDrawRandom(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CharacterDrawRandom'](arg1, arg2, arg3, arg4);
}

export function CharacterFillAll() {
  return window['go']['app']['App']['CharacterFillAll']();
}

export function CharacterGenerateFill(arg1) {
  return window['go']['app']['App']['CharacterGenerateFill'](arg1);
}

export function CharacterGeneratePortrait(arg1, arg2) {
  return window['go']['app']['App']['CharacterGeneratePortrait'](arg1, arg2);
}

export function CharacterGenerateRandom(arg1, arg2) {
  return window['go']['app']['App']['CharacterGenerateRandom'](arg1, arg2);
}

export function CharacterGet(arg1) {
  return window['go']['app']['App']['CharacterGet'](arg1);
}

export function CharacterImportProject() {
  return window['go']['app']['App']['CharacterImportProject']();
}

export function CharacterList(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['CharacterList'](arg1, arg2, arg3, arg4, arg5);
}

export function CharacterListByProject() {
  return window['go']['app']['App']['CharacterListByProject']();
}

export function CharacterSave(arg1) {
  return window['go']['app']['App']['CharacterSave'](arg1);
}

export function CharacterSetProjectState(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CharacterSetProjectState'](arg1, arg2, arg3, arg4);
}

export function CharacterSyncProject() {
  return window['go']['app']['App']['CharacterSyncProject']();
}

export function Chat(arg1, arg2) {
  return window['go']['app']['App']['Chat'](arg1, arg2);
}

export function ChatCharacter(arg1) {
  return window['go']['app']['App']['ChatCharacter'](arg1);
}

export function ChatCharacterDetail(arg1, arg2) {
  return window['go']['app']['App']['ChatCharacterDetail'](arg1, arg2);
}

export function ChatGeneral(arg1) {
  return window['go']['app']['App']['ChatGeneral'](arg1);
}

export function ChatImportTopic(arg1, arg2, arg3) {
  return window['go']['app']['App']['ChatImportTopic'](arg1, arg2, arg3);
}

export function ChatMessagesList(arg1) {
  return window['go']['app']['App']['ChatMessagesList'](arg1);
}

export function ChatOutline(arg1) {
  return window['go']['app']['App']['ChatOutline'](arg1);
}

export function ChatOutlineNode(arg1, arg2) {
  return window['go']['app']['App']['ChatOutlineNode'](arg1, arg2);
}

export function ChatSend(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ChatSend'](arg1, arg2, arg3, arg4);
}

export function ChatTopicClear(arg1) {
  return window['go']['app']['App']['ChatTopicClear'](arg1);
}

export function ChatTopicCreate(arg1, arg2) {
  return window['go']['app']['App']['ChatTopicCreate'](arg1, arg2);
}

export function ChatTopicDelete(arg1) {
  return window['go']['app']['App']['ChatTopicDelete'](arg1);
}

export function ChatTopicRename(arg1, arg2) {
  return window['go']['app']['App']['ChatTopicRename'](arg1, arg2);
}

export function ChatTopicSetMode(arg1, arg2) {
  return window['go']['app']['App']['ChatTopicSetMode'](arg1, arg2);
}

export function ChatTopicsList() {
  return window['go']['app']['App']['ChatTopicsList']();
}

export function ChatWorldview(arg1, arg2) {
  return window['go']['app']['App']['ChatWorldview'](arg1, arg2);
}

export function CheckConsistency() {
  return window['go']['app']['App']['CheckConsistency']();
}

export function CloseProject() {
  return window['go']['app']['App']['CloseProject']();
}

export function CmdKEdit(arg1, arg2, arg3) {
  return window['go']['app']['App']['CmdKEdit'](arg1, arg2, arg3);
}

export function ContinueOutline(arg1) {
  return window['go']['app']['App']['ContinueOutline'](arg1);
}

export function CreateChapter(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['CreateChapter'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function CreateProject(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateProject'](arg1, arg2, arg3, arg4);
}

export function CreateSnapshot(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateSnapshot'](arg1, arg2, arg3);
}

export function DeleteCharacter(arg1) {
  return window['go']['app']['App']['DeleteCharacter'](arg1);
}

export function DeleteLorebookEntry(arg1) {
  return window['go']['app']['App']['DeleteLorebookEntry'](arg1);
}

export function DeleteOrganization(arg1) {
  return window['go']['app']['App']['DeleteOrganization'](arg1);
}

export function DeleteOutlineNode(arg1) {
  return window['go']['app']['App']['DeleteOutlineNode'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['app']['App']['DeleteProject'](arg1);
}

export function DeleteRelationship(arg1, arg2) {
  return window['go']['app']['App']['DeleteRelationship'](arg1, arg2);
}

export function ExpandOutlineNode(arg1, arg2) {
  return window['go']['app']['App']['ExpandOutlineNode'](arg1, arg2);
}

export function ExportAll() {
  return window['go']['app']['App']['ExportAll']();
}

export function ExportHTML(arg1) {
  return window['go']['app']['App']['ExportHTML'](arg1);
}

export function ExtractCharacterHeatmap() {
  return window['go']['app']['App']['ExtractCharacterHeatmap']();
}

export function ExtractEmotionCurve() {
  return window['go']['app']['App']['ExtractEmotionCurve']();
}

export function ExtractTimeline() {
  return window['go']['app']['App']['ExtractTimeline']();
}

export function FindLorebookTriggers(arg1) {
  return window['go']['app']['App']['FindLorebookTriggers'](arg1);
}

export function FindUnlinkedMentions(arg1, arg2) {
  return window['go']['app']['App']['FindUnlinkedMentions'](arg1, arg2);
}

export function GaeaAcceptMemorySuggestion(arg1) {
  return window['go']['app']['App']['GaeaAcceptMemorySuggestion'](arg1);
}

export function GaeaAcceptSkillSuggestion(arg1) {
  return window['go']['app']['App']['GaeaAcceptSkillSuggestion'](arg1);
}

export function GaeaAddMCPServer(arg1) {
  return window['go']['app']['App']['GaeaAddMCPServer'](arg1);
}

export function GaeaAddPermissionRule(arg1, arg2) {
  return window['go']['app']['App']['GaeaAddPermissionRule'](arg1, arg2);
}

export function GaeaAgentMode() {
  return window['go']['app']['App']['GaeaAgentMode']();
}

export function GaeaAnswer(arg1, arg2) {
  return window['go']['app']['App']['GaeaAnswer'](arg1, arg2);
}

export function GaeaApplyUpdate() {
  return window['go']['app']['App']['GaeaApplyUpdate']();
}

export function GaeaApprove(arg1, arg2, arg3) {
  return window['go']['app']['App']['GaeaApprove'](arg1, arg2, arg3);
}

export function GaeaAttachmentDataURL(arg1) {
  return window['go']['app']['App']['GaeaAttachmentDataURL'](arg1);
}

export function GaeaBalance() {
  return window['go']['app']['App']['GaeaBalance']();
}

export function GaeaCallTool(arg1, arg2) {
  return window['go']['app']['App']['GaeaCallTool'](arg1, arg2);
}

export function GaeaCancel() {
  return window['go']['app']['App']['GaeaCancel']();
}

export function GaeaCapabilities() {
  return window['go']['app']['App']['GaeaCapabilities']();
}

export function GaeaCaptureScreen() {
  return window['go']['app']['App']['GaeaCaptureScreen']();
}

export function GaeaCaptureSkill(arg1) {
  return window['go']['app']['App']['GaeaCaptureSkill'](arg1);
}

export function GaeaChangeFactType(arg1, arg2) {
  return window['go']['app']['App']['GaeaChangeFactType'](arg1, arg2);
}

export function GaeaCheckUpdate() {
  return window['go']['app']['App']['GaeaCheckUpdate']();
}

export function GaeaCheckpoints() {
  return window['go']['app']['App']['GaeaCheckpoints']();
}

export function GaeaCommands() {
  return window['go']['app']['App']['GaeaCommands']();
}

export function GaeaContext() {
  return window['go']['app']['App']['GaeaContext']();
}

export function GaeaCostDelete(arg1) {
  return window['go']['app']['App']['GaeaCostDelete'](arg1);
}

export function GaeaCostGet(arg1) {
  return window['go']['app']['App']['GaeaCostGet'](arg1);
}

export function GaeaCostImportAIParse(arg1) {
  return window['go']['app']['App']['GaeaCostImportAIParse'](arg1);
}

export function GaeaCostImportApply(arg1) {
  return window['go']['app']['App']['GaeaCostImportApply'](arg1);
}

export function GaeaCostImportPreview(arg1) {
  return window['go']['app']['App']['GaeaCostImportPreview'](arg1);
}

export function GaeaCostList() {
  return window['go']['app']['App']['GaeaCostList']();
}

export function GaeaCostSave(arg1) {
  return window['go']['app']['App']['GaeaCostSave'](arg1);
}

export function GaeaCostSearch(arg1, arg2, arg3) {
  return window['go']['app']['App']['GaeaCostSearch'](arg1, arg2, arg3);
}

export function GaeaCrossEmbed(arg1) {
  return window['go']['app']['App']['GaeaCrossEmbed'](arg1);
}

export function GaeaDeleteProvider(arg1) {
  return window['go']['app']['App']['GaeaDeleteProvider'](arg1);
}

export function GaeaDeleteSession(arg1) {
  return window['go']['app']['App']['GaeaDeleteSession'](arg1);
}

export function GaeaDocxAcceptChanges(arg1, arg2) {
  return window['go']['app']['App']['GaeaDocxAcceptChanges'](arg1, arg2);
}

export function GaeaDocxApplyEdit(arg1, arg2, arg3) {
  return window['go']['app']['App']['GaeaDocxApplyEdit'](arg1, arg2, arg3);
}

export function GaeaEngines() {
  return window['go']['app']['App']['GaeaEngines']();
}

export function GaeaExportDeliverable(arg1) {
  return window['go']['app']['App']['GaeaExportDeliverable'](arg1);
}

export function GaeaFactBase() {
  return window['go']['app']['App']['GaeaFactBase']();
}

export function GaeaFactBaseClear() {
  return window['go']['app']['App']['GaeaFactBaseClear']();
}

export function GaeaFactBasePromote() {
  return window['go']['app']['App']['GaeaFactBasePromote']();
}

export function GaeaFileIndexRebuild() {
  return window['go']['app']['App']['GaeaFileIndexRebuild']();
}

export function GaeaFileSearch(arg1, arg2) {
  return window['go']['app']['App']['GaeaFileSearch'](arg1, arg2);
}

export function GaeaFileSemanticSearch(arg1, arg2) {
  return window['go']['app']['App']['GaeaFileSemanticSearch'](arg1, arg2);
}

export function GaeaForget(arg1) {
  return window['go']['app']['App']['GaeaForget'](arg1);
}

export function GaeaFork(arg1) {
  return window['go']['app']['App']['GaeaFork'](arg1);
}

export function GaeaHistory() {
  return window['go']['app']['App']['GaeaHistory']();
}

export function GaeaInit() {
  return window['go']['app']['App']['GaeaInit']();
}

export function GaeaJobs() {
  return window['go']['app']['App']['GaeaJobs']();
}

export function GaeaKnowledgeDelete(arg1) {
  return window['go']['app']['App']['GaeaKnowledgeDelete'](arg1);
}

export function GaeaKnowledgeExport(arg1) {
  return window['go']['app']['App']['GaeaKnowledgeExport'](arg1);
}

export function GaeaKnowledgeFindSimilar(arg1) {
  return window['go']['app']['App']['GaeaKnowledgeFindSimilar'](arg1);
}

export function GaeaKnowledgeGet(arg1) {
  return window['go']['app']['App']['GaeaKnowledgeGet'](arg1);
}

export function GaeaKnowledgeHistory(arg1) {
  return window['go']['app']['App']['GaeaKnowledgeHistory'](arg1);
}

export function GaeaKnowledgeImportAIParse(arg1) {
  return window['go']['app']['App']['GaeaKnowledgeImportAIParse'](arg1);
}

export function GaeaKnowledgeImportApply(arg1) {
  return window['go']['app']['App']['GaeaKnowledgeImportApply'](arg1);
}

export function GaeaKnowledgeImportPreview(arg1) {
  return window['go']['app']['App']['GaeaKnowledgeImportPreview'](arg1);
}

export function GaeaKnowledgeList() {
  return window['go']['app']['App']['GaeaKnowledgeList']();
}

export function GaeaKnowledgeMerge(arg1, arg2) {
  return window['go']['app']['App']['GaeaKnowledgeMerge'](arg1, arg2);
}

export function GaeaKnowledgeReview(arg1, arg2, arg3) {
  return window['go']['app']['App']['GaeaKnowledgeReview'](arg1, arg2, arg3);
}

export function GaeaKnowledgeSave(arg1) {
  return window['go']['app']['App']['GaeaKnowledgeSave'](arg1);
}

export function GaeaKnowledgeSearch(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GaeaKnowledgeSearch'](arg1, arg2, arg3, arg4);
}

export function GaeaListDir(arg1) {
  return window['go']['app']['App']['GaeaListDir'](arg1);
}

export function GaeaListSessions() {
  return window['go']['app']['App']['GaeaListSessions']();
}

export function GaeaListWorkspaces() {
  return window['go']['app']['App']['GaeaListWorkspaces']();
}

export function GaeaLoginProvider(arg1) {
  return window['go']['app']['App']['GaeaLoginProvider'](arg1);
}

export function GaeaLogoutProvider(arg1) {
  return window['go']['app']['App']['GaeaLogoutProvider'](arg1);
}

export function GaeaMaterials(arg1) {
  return window['go']['app']['App']['GaeaMaterials'](arg1);
}

export function GaeaMemory() {
  return window['go']['app']['App']['GaeaMemory']();
}

export function GaeaMemoryDuplicates(arg1) {
  return window['go']['app']['App']['GaeaMemoryDuplicates'](arg1);
}

export function GaeaMemoryGraph() {
  return window['go']['app']['App']['GaeaMemoryGraph']();
}

export function GaeaMemoryHubOverview() {
  return window['go']['app']['App']['GaeaMemoryHubOverview']();
}

export function GaeaMemoryMerge(arg1, arg2) {
  return window['go']['app']['App']['GaeaMemoryMerge'](arg1, arg2);
}

export function GaeaMemorySuggestions() {
  return window['go']['app']['App']['GaeaMemorySuggestions']();
}

export function GaeaMeta() {
  return window['go']['app']['App']['GaeaMeta']();
}

export function GaeaModel() {
  return window['go']['app']['App']['GaeaModel']();
}

export function GaeaModels() {
  return window['go']['app']['App']['GaeaModels']();
}

export function GaeaNewSession() {
  return window['go']['app']['App']['GaeaNewSession']();
}

export function GaeaOCRText(arg1) {
  return window['go']['app']['App']['GaeaOCRText'](arg1);
}

export function GaeaOfficeEditText(arg1, arg2) {
  return window['go']['app']['App']['GaeaOfficeEditText'](arg1, arg2);
}

export function GaeaOpenDownloadPage() {
  return window['go']['app']['App']['GaeaOpenDownloadPage']();
}

export function GaeaOpenWorkspacePath(arg1) {
  return window['go']['app']['App']['GaeaOpenWorkspacePath'](arg1);
}

export function GaeaPermLevel() {
  return window['go']['app']['App']['GaeaPermLevel']();
}

export function GaeaPickDirectory() {
  return window['go']['app']['App']['GaeaPickDirectory']();
}

export function GaeaPickFiles() {
  return window['go']['app']['App']['GaeaPickFiles']();
}

export function GaeaPickWorkspace() {
  return window['go']['app']['App']['GaeaPickWorkspace']();
}

export function GaeaPinMaterial(arg1) {
  return window['go']['app']['App']['GaeaPinMaterial'](arg1);
}

export function GaeaPinnedMaterials() {
  return window['go']['app']['App']['GaeaPinnedMaterials']();
}

export function GaeaPreview(arg1) {
  return window['go']['app']['App']['GaeaPreview'](arg1);
}

export function GaeaPriceFetch(arg1) {
  return window['go']['app']['App']['GaeaPriceFetch'](arg1);
}

export function GaeaPriceFetchApply(arg1, arg2) {
  return window['go']['app']['App']['GaeaPriceFetchApply'](arg1, arg2);
}

export function GaeaPriceFetchIgnore(arg1) {
  return window['go']['app']['App']['GaeaPriceFetchIgnore'](arg1);
}

export function GaeaPriceFetches() {
  return window['go']['app']['App']['GaeaPriceFetches']();
}

export function GaeaPriceHistory(arg1) {
  return window['go']['app']['App']['GaeaPriceHistory'](arg1);
}

export function GaeaPriceSourceDelete(arg1) {
  return window['go']['app']['App']['GaeaPriceSourceDelete'](arg1);
}

export function GaeaPriceSourceSave(arg1) {
  return window['go']['app']['App']['GaeaPriceSourceSave'](arg1);
}

export function GaeaPriceSources() {
  return window['go']['app']['App']['GaeaPriceSources']();
}

export function GaeaProfileConflicts() {
  return window['go']['app']['App']['GaeaProfileConflicts']();
}

export function GaeaProfileDelete(arg1) {
  return window['go']['app']['App']['GaeaProfileDelete'](arg1);
}

export function GaeaProfileList() {
  return window['go']['app']['App']['GaeaProfileList']();
}

export function GaeaProfileResolveConflict(arg1, arg2) {
  return window['go']['app']['App']['GaeaProfileResolveConflict'](arg1, arg2);
}

export function GaeaProfileSave(arg1) {
  return window['go']['app']['App']['GaeaProfileSave'](arg1);
}

export function GaeaReadFile(arg1) {
  return window['go']['app']['App']['GaeaReadFile'](arg1);
}

export function GaeaRecognizeImage(arg1, arg2) {
  return window['go']['app']['App']['GaeaRecognizeImage'](arg1, arg2);
}

export function GaeaReload() {
  return window['go']['app']['App']['GaeaReload']();
}

export function GaeaRemember(arg1, arg2) {
  return window['go']['app']['App']['GaeaRemember'](arg1, arg2);
}

export function GaeaRemoveMCPServer(arg1) {
  return window['go']['app']['App']['GaeaRemoveMCPServer'](arg1);
}

export function GaeaRemovePermissionRule(arg1, arg2) {
  return window['go']['app']['App']['GaeaRemovePermissionRule'](arg1, arg2);
}

export function GaeaRenameSession(arg1, arg2) {
  return window['go']['app']['App']['GaeaRenameSession'](arg1, arg2);
}

export function GaeaResumeSession(arg1) {
  return window['go']['app']['App']['GaeaResumeSession'](arg1);
}

export function GaeaRetryMCPServer(arg1) {
  return window['go']['app']['App']['GaeaRetryMCPServer'](arg1);
}

export function GaeaRevealWorkspacePath(arg1) {
  return window['go']['app']['App']['GaeaRevealWorkspacePath'](arg1);
}

export function GaeaRewind(arg1, arg2) {
  return window['go']['app']['App']['GaeaRewind'](arg1, arg2);
}

export function GaeaRunning() {
  return window['go']['app']['App']['GaeaRunning']();
}

export function GaeaSaveAttachmentFile(arg1, arg2) {
  return window['go']['app']['App']['GaeaSaveAttachmentFile'](arg1, arg2);
}

export function GaeaSaveDoc(arg1, arg2) {
  return window['go']['app']['App']['GaeaSaveDoc'](arg1, arg2);
}

export function GaeaSavePastedImage(arg1) {
  return window['go']['app']['App']['GaeaSavePastedImage'](arg1);
}

export function GaeaSaveProvider(arg1) {
  return window['go']['app']['App']['GaeaSaveProvider'](arg1);
}

export function GaeaSaveSettings(arg1) {
  return window['go']['app']['App']['GaeaSaveSettings'](arg1);
}

export function GaeaSaveWindowState(arg1) {
  return window['go']['app']['App']['GaeaSaveWindowState'](arg1);
}

export function GaeaSelectTab(arg1) {
  return window['go']['app']['App']['GaeaSelectTab'](arg1);
}

export function GaeaSemanticSearch(arg1) {
  return window['go']['app']['App']['GaeaSemanticSearch'](arg1);
}

export function GaeaSend(arg1) {
  return window['go']['app']['App']['GaeaSend'](arg1);
}

export function GaeaSetAgentParams(arg1, arg2, arg3) {
  return window['go']['app']['App']['GaeaSetAgentParams'](arg1, arg2, arg3);
}

export function GaeaSetDefaultModel(arg1) {
  return window['go']['app']['App']['GaeaSetDefaultModel'](arg1);
}

export function GaeaSetEngine(arg1) {
  return window['go']['app']['App']['GaeaSetEngine'](arg1);
}

export function GaeaSetMCPServerEnabled(arg1, arg2) {
  return window['go']['app']['App']['GaeaSetMCPServerEnabled'](arg1, arg2);
}

export function GaeaSetMemoryEnabled(arg1) {
  return window['go']['app']['App']['GaeaSetMemoryEnabled'](arg1);
}

export function GaeaSetModel(arg1) {
  return window['go']['app']['App']['GaeaSetModel'](arg1);
}

export function GaeaSetPermLevel(arg1) {
  return window['go']['app']['App']['GaeaSetPermLevel'](arg1);
}

export function GaeaSetPermissionMode(arg1) {
  return window['go']['app']['App']['GaeaSetPermissionMode'](arg1);
}

export function GaeaSetProviderKey(arg1, arg2) {
  return window['go']['app']['App']['GaeaSetProviderKey'](arg1, arg2);
}

export function GaeaSetSandbox(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GaeaSetSandbox'](arg1, arg2, arg3, arg4);
}

export function GaeaSetSubagentEffort(arg1) {
  return window['go']['app']['App']['GaeaSetSubagentEffort'](arg1);
}

export function GaeaSetSubagentModelForSkill(arg1, arg2) {
  return window['go']['app']['App']['GaeaSetSubagentModelForSkill'](arg1, arg2);
}

export function GaeaSettings() {
  return window['go']['app']['App']['GaeaSettings']();
}

export function GaeaSkills() {
  return window['go']['app']['App']['GaeaSkills']();
}

export function GaeaSlashArgs(arg1) {
  return window['go']['app']['App']['GaeaSlashArgs'](arg1);
}

export function GaeaSummarizeFile(arg1, arg2) {
  return window['go']['app']['App']['GaeaSummarizeFile'](arg1, arg2);
}

export function GaeaSummarizeFrom(arg1) {
  return window['go']['app']['App']['GaeaSummarizeFrom'](arg1);
}

export function GaeaSummarizeUpTo(arg1) {
  return window['go']['app']['App']['GaeaSummarizeUpTo'](arg1);
}

export function GaeaSwitchWorkspace(arg1) {
  return window['go']['app']['App']['GaeaSwitchWorkspace'](arg1);
}

export function GaeaTCCAReport() {
  return window['go']['app']['App']['GaeaTCCAReport']();
}

export function GaeaTabMeta() {
  return window['go']['app']['App']['GaeaTabMeta']();
}

export function GaeaTaskTemplates() {
  return window['go']['app']['App']['GaeaTaskTemplates']();
}

export function GaeaTools() {
  return window['go']['app']['App']['GaeaTools']();
}

export function GaeaUnpinMaterial(arg1) {
  return window['go']['app']['App']['GaeaUnpinMaterial'](arg1);
}

export function GaeaUpdateFact(arg1, arg2) {
  return window['go']['app']['App']['GaeaUpdateFact'](arg1, arg2);
}

export function GaeaVersion() {
  return window['go']['app']['App']['GaeaVersion']();
}

export function GaeaWhisperEpisodes() {
  return window['go']['app']['App']['GaeaWhisperEpisodes']();
}

export function GaeaWhisperExportArchive(arg1) {
  return window['go']['app']['App']['GaeaWhisperExportArchive'](arg1);
}

export function GaeaWhisperMemories() {
  return window['go']['app']['App']['GaeaWhisperMemories']();
}

export function GaeaWorkspaceChanges() {
  return window['go']['app']['App']['GaeaWorkspaceChanges']();
}

export function GaeaWorkspaceSearch(arg1, arg2) {
  return window['go']['app']['App']['GaeaWorkspaceSearch'](arg1, arg2);
}

export function GaeaXlsxColOps(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GaeaXlsxColOps'](arg1, arg2, arg3, arg4);
}

export function GaeaXlsxEdit(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GaeaXlsxEdit'](arg1, arg2, arg3, arg4);
}

export function GaeaXlsxRecalc(arg1) {
  return window['go']['app']['App']['GaeaXlsxRecalc'](arg1);
}

export function GaeaXlsxRowOps(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GaeaXlsxRowOps'](arg1, arg2, arg3, arg4);
}

export function GaeaXlsxSetCell(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['GaeaXlsxSetCell'](arg1, arg2, arg3, arg4);
}

export function GenerateCharacterPortrait(arg1, arg2) {
  return window['go']['app']['App']['GenerateCharacterPortrait'](arg1, arg2);
}

export function GenerateCharacters(arg1) {
  return window['go']['app']['App']['GenerateCharacters'](arg1);
}

export function GenerateDefaultCanvas() {
  return window['go']['app']['App']['GenerateDefaultCanvas']();
}

export function GenerateDiagram(arg1) {
  return window['go']['app']['App']['GenerateDiagram'](arg1);
}

export function GenerateFreeImage(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['app']['App']['GenerateFreeImage'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function GenerateMedia(arg1) {
  return window['go']['app']['App']['GenerateMedia'](arg1);
}

export function GenerateOutlineWithDialogue(arg1, arg2, arg3) {
  return window['go']['app']['App']['GenerateOutlineWithDialogue'](arg1, arg2, arg3);
}

export function GenerateProjectCharacterFill(arg1) {
  return window['go']['app']['App']['GenerateProjectCharacterFill'](arg1);
}

export function GenerateSceneIllustration(arg1) {
  return window['go']['app']['App']['GenerateSceneIllustration'](arg1);
}

export function GenerateSingleCharacter(arg1) {
  return window['go']['app']['App']['GenerateSingleCharacter'](arg1);
}

export function GetActiveASRModel() {
  return window['go']['app']['App']['GetActiveASRModel']();
}

export function GetActiveEngine() {
  return window['go']['app']['App']['GetActiveEngine']();
}

export function GetActiveModel() {
  return window['go']['app']['App']['GetActiveModel']();
}

export function GetActiveTTSModel() {
  return window['go']['app']['App']['GetActiveTTSModel']();
}

export function GetAllEntityNames() {
  return window['go']['app']['App']['GetAllEntityNames']();
}

export function GetAppInfo() {
  return window['go']['app']['App']['GetAppInfo']();
}

export function GetBacklinks(arg1) {
  return window['go']['app']['App']['GetBacklinks'](arg1);
}

export function GetBookData() {
  return window['go']['app']['App']['GetBookData']();
}

export function GetChapter(arg1) {
  return window['go']['app']['App']['GetChapter'](arg1);
}

export function GetChapterBranch(arg1, arg2) {
  return window['go']['app']['App']['GetChapterBranch'](arg1, arg2);
}

export function GetChapterScenes(arg1) {
  return window['go']['app']['App']['GetChapterScenes'](arg1);
}

export function GetCharacters() {
  return window['go']['app']['App']['GetCharacters']();
}

export function GetChatVoiceModel() {
  return window['go']['app']['App']['GetChatVoiceModel']();
}

export function GetComfyUILoras() {
  return window['go']['app']['App']['GetComfyUILoras']();
}

export function GetComfyUIStatus() {
  return window['go']['app']['App']['GetComfyUIStatus']();
}

export function GetCompileTemplates() {
  return window['go']['app']['App']['GetCompileTemplates']();
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetDashboard(arg1) {
  return window['go']['app']['App']['GetDashboard'](arg1);
}

export function GetDeepseekKeyStatus() {
  return window['go']['app']['App']['GetDeepseekKeyStatus']();
}

export function GetEngineList() {
  return window['go']['app']['App']['GetEngineList']();
}

export function GetEngines() {
  return window['go']['app']['App']['GetEngines']();
}

export function GetEntityRelations() {
  return window['go']['app']['App']['GetEntityRelations']();
}

export function GetFeatureModel(arg1) {
  return window['go']['app']['App']['GetFeatureModel'](arg1);
}

export function GetFeatureModelEnabled(arg1) {
  return window['go']['app']['App']['GetFeatureModelEnabled'](arg1);
}

export function GetForeshadows() {
  return window['go']['app']['App']['GetForeshadows']();
}

export function GetImageBackend() {
  return window['go']['app']['App']['GetImageBackend']();
}

export function GetImageBackendConfig() {
  return window['go']['app']['App']['GetImageBackendConfig']();
}

export function GetImageBackendInfo() {
  return window['go']['app']['App']['GetImageBackendInfo']();
}

export function GetLoginStatus() {
  return window['go']['app']['App']['GetLoginStatus']();
}

export function GetLorebookEntries() {
  return window['go']['app']['App']['GetLorebookEntries']();
}

export function GetModelCallStats() {
  return window['go']['app']['App']['GetModelCallStats']();
}

export function GetModelMonitor() {
  return window['go']['app']['App']['GetModelMonitor']();
}

export function GetModelRoute(arg1) {
  return window['go']['app']['App']['GetModelRoute'](arg1);
}

export function GetNovelsDir() {
  return window['go']['app']['App']['GetNovelsDir']();
}

export function GetOpencodeGoKeyStatus() {
  return window['go']['app']['App']['GetOpencodeGoKeyStatus']();
}

export function GetOpencodeZenKeyStatus() {
  return window['go']['app']['App']['GetOpencodeZenKeyStatus']();
}

export function GetOutlines() {
  return window['go']['app']['App']['GetOutlines']();
}

export function GetPortraitConfig() {
  return window['go']['app']['App']['GetPortraitConfig']();
}

export function GetProjectInfo() {
  return window['go']['app']['App']['GetProjectInfo']();
}

export function GetStats() {
  return window['go']['app']['App']['GetStats']();
}

export function GetStyleProfile() {
  return window['go']['app']['App']['GetStyleProfile']();
}

export function GetSystemStats() {
  return window['go']['app']['App']['GetSystemStats']();
}

export function GetTTSConfig() {
  return window['go']['app']['App']['GetTTSConfig']();
}

export function GetTTSSpeakers(arg1) {
  return window['go']['app']['App']['GetTTSSpeakers'](arg1);
}

export function GetTTSStatus() {
  return window['go']['app']['App']['GetTTSStatus']();
}

export function GetVoicePipelineConfig() {
  return window['go']['app']['App']['GetVoicePipelineConfig']();
}

export function GetWorldMapImage() {
  return window['go']['app']['App']['GetWorldMapImage']();
}

export function GetWorldview() {
  return window['go']['app']['App']['GetWorldview']();
}

export function GetWorldviewSections() {
  return window['go']['app']['App']['GetWorldviewSections']();
}

export function ImportStyleProfile(arg1, arg2) {
  return window['go']['app']['App']['ImportStyleProfile'](arg1, arg2);
}

export function InjectMemories(arg1, arg2, arg3) {
  return window['go']['app']['App']['InjectMemories'](arg1, arg2, arg3);
}

export function IsProjectV4() {
  return window['go']['app']['App']['IsProjectV4']();
}

export function ListProjects() {
  return window['go']['app']['App']['ListProjects']();
}

export function ListSkills() {
  return window['go']['app']['App']['ListSkills']();
}

export function ListSnapshots(arg1, arg2) {
  return window['go']['app']['App']['ListSnapshots'](arg1, arg2);
}

export function Login() {
  return window['go']['app']['App']['Login']();
}

export function Logout() {
  return window['go']['app']['App']['Logout']();
}

export function MainBrainChat(arg1) {
  return window['go']['app']['App']['MainBrainChat'](arg1);
}

export function MergeCharacters(arg1, arg2) {
  return window['go']['app']['App']['MergeCharacters'](arg1, arg2);
}

export function MigrateProjectToV4() {
  return window['go']['app']['App']['MigrateProjectToV4']();
}

export function OfficeCancelJob(arg1) {
  return window['go']['app']['App']['OfficeCancelJob'](arg1);
}

export function OfficeExecute(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['app']['App']['OfficeExecute'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function OfficeGetJobState(arg1) {
  return window['go']['app']['App']['OfficeGetJobState'](arg1);
}

export function OfficeGetMode(arg1) {
  return window['go']['app']['App']['OfficeGetMode'](arg1);
}

export function OfficeIsTask(arg1) {
  return window['go']['app']['App']['OfficeIsTask'](arg1);
}

export function OfficeListFolder(arg1) {
  return window['go']['app']['App']['OfficeListFolder'](arg1);
}

export function OfficeReadFile(arg1) {
  return window['go']['app']['App']['OfficeReadFile'](arg1);
}

export function OfficeSetMode(arg1, arg2) {
  return window['go']['app']['App']['OfficeSetMode'](arg1, arg2);
}

export function OpenImageSaveDir() {
  return window['go']['app']['App']['OpenImageSaveDir']();
}

export function OpenNovelImagesDir() {
  return window['go']['app']['App']['OpenNovelImagesDir']();
}

export function OpenProject(arg1) {
  return window['go']['app']['App']['OpenProject'](arg1);
}

export function ParseLinks(arg1) {
  return window['go']['app']['App']['ParseLinks'](arg1);
}

export function ProposalAddSection(arg1, arg2, arg3) {
  return window['go']['app']['App']['ProposalAddSection'](arg1, arg2, arg3);
}

export function ProposalArchive(arg1) {
  return window['go']['app']['App']['ProposalArchive'](arg1);
}

export function ProposalAssetAdd(arg1, arg2, arg3) {
  return window['go']['app']['App']['ProposalAssetAdd'](arg1, arg2, arg3);
}

export function ProposalAssetRemove(arg1) {
  return window['go']['app']['App']['ProposalAssetRemove'](arg1);
}

export function ProposalAssetsList() {
  return window['go']['app']['App']['ProposalAssetsList']();
}

export function ProposalBatchCancel(arg1) {
  return window['go']['app']['App']['ProposalBatchCancel'](arg1);
}

export function ProposalBatchGenerate(arg1) {
  return window['go']['app']['App']['ProposalBatchGenerate'](arg1);
}

export function ProposalCheckAll(arg1) {
  return window['go']['app']['App']['ProposalCheckAll'](arg1);
}

export function ProposalCheckCompliance(arg1) {
  return window['go']['app']['App']['ProposalCheckCompliance'](arg1);
}

export function ProposalCheckCoverage(arg1) {
  return window['go']['app']['App']['ProposalCheckCoverage'](arg1);
}

export function ProposalConvertFiles(arg1) {
  return window['go']['app']['App']['ProposalConvertFiles'](arg1);
}

export function ProposalCreate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['ProposalCreate'](arg1, arg2, arg3, arg4, arg5);
}

export function ProposalDarkRuleDelete(arg1) {
  return window['go']['app']['App']['ProposalDarkRuleDelete'](arg1);
}

export function ProposalDarkRuleSave(arg1) {
  return window['go']['app']['App']['ProposalDarkRuleSave'](arg1);
}

export function ProposalDarkRulesList() {
  return window['go']['app']['App']['ProposalDarkRulesList']();
}

export function ProposalDelete(arg1) {
  return window['go']['app']['App']['ProposalDelete'](arg1);
}

export function ProposalExport(arg1) {
  return window['go']['app']['App']['ProposalExport'](arg1);
}

export function ProposalExportDocx(arg1) {
  return window['go']['app']['App']['ProposalExportDocx'](arg1);
}

export function ProposalExportDocxWithOptions(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ProposalExportDocxWithOptions'](arg1, arg2, arg3, arg4);
}

export function ProposalExportSectionDocx(arg1, arg2) {
  return window['go']['app']['App']['ProposalExportSectionDocx'](arg1, arg2);
}

export function ProposalGenerateChart(arg1, arg2, arg3) {
  return window['go']['app']['App']['ProposalGenerateChart'](arg1, arg2, arg3);
}

export function ProposalGenerateOutline(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ProposalGenerateOutline'](arg1, arg2, arg3, arg4);
}

export function ProposalGenerateSection(arg1, arg2, arg3) {
  return window['go']['app']['App']['ProposalGenerateSection'](arg1, arg2, arg3);
}

export function ProposalGenerateSectionStream(arg1, arg2, arg3) {
  return window['go']['app']['App']['ProposalGenerateSectionStream'](arg1, arg2, arg3);
}

export function ProposalGet(arg1) {
  return window['go']['app']['App']['ProposalGet'](arg1);
}

export function ProposalImportOutline(arg1, arg2) {
  return window['go']['app']['App']['ProposalImportOutline'](arg1, arg2);
}

export function ProposalList() {
  return window['go']['app']['App']['ProposalList']();
}

export function ProposalMoveSection(arg1, arg2, arg3) {
  return window['go']['app']['App']['ProposalMoveSection'](arg1, arg2, arg3);
}

export function ProposalParseBidFile(arg1) {
  return window['go']['app']['App']['ProposalParseBidFile'](arg1);
}

export function ProposalParseBidFileWithProgress(arg1) {
  return window['go']['app']['App']['ProposalParseBidFileWithProgress'](arg1);
}

export function ProposalPolish(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ProposalPolish'](arg1, arg2, arg3, arg4);
}

export function ProposalProjectCreate(arg1, arg2, arg3) {
  return window['go']['app']['App']['ProposalProjectCreate'](arg1, arg2, arg3);
}

export function ProposalProjectDelete(arg1) {
  return window['go']['app']['App']['ProposalProjectDelete'](arg1);
}

export function ProposalProjectFactsGet(arg1) {
  return window['go']['app']['App']['ProposalProjectFactsGet'](arg1);
}

export function ProposalProjectFactsSet(arg1, arg2) {
  return window['go']['app']['App']['ProposalProjectFactsSet'](arg1, arg2);
}

export function ProposalProjectList() {
  return window['go']['app']['App']['ProposalProjectList']();
}

export function ProposalReadFile(arg1) {
  return window['go']['app']['App']['ProposalReadFile'](arg1);
}

export function ProposalRemoveRawFile(arg1, arg2) {
  return window['go']['app']['App']['ProposalRemoveRawFile'](arg1, arg2);
}

export function ProposalRemoveSection(arg1, arg2) {
  return window['go']['app']['App']['ProposalRemoveSection'](arg1, arg2);
}

export function ProposalRenameSection(arg1, arg2, arg3) {
  return window['go']['app']['App']['ProposalRenameSection'](arg1, arg2, arg3);
}

export function ProposalRunPipeline(arg1) {
  return window['go']['app']['App']['ProposalRunPipeline'](arg1);
}

export function ProposalSaveRawText(arg1, arg2) {
  return window['go']['app']['App']['ProposalSaveRawText'](arg1, arg2);
}

export function ProposalSaveUploadedFile(arg1, arg2, arg3) {
  return window['go']['app']['App']['ProposalSaveUploadedFile'](arg1, arg2, arg3);
}

export function ProposalTemplates() {
  return window['go']['app']['App']['ProposalTemplates']();
}

export function ProposalUpdate(arg1) {
  return window['go']['app']['App']['ProposalUpdate'](arg1);
}

export function QueryEntities(arg1) {
  return window['go']['app']['App']['QueryEntities'](arg1);
}

export function QuickBrainstormBranches(arg1, arg2) {
  return window['go']['app']['App']['QuickBrainstormBranches'](arg1, arg2);
}

export function RefreshEngineModels(arg1) {
  return window['go']['app']['App']['RefreshEngineModels'](arg1);
}

export function ReorderScenes(arg1, arg2) {
  return window['go']['app']['App']['ReorderScenes'](arg1, arg2);
}

export function ResetModelCallStats() {
  return window['go']['app']['App']['ResetModelCallStats']();
}

export function RestoreSnapshot(arg1, arg2, arg3) {
  return window['go']['app']['App']['RestoreSnapshot'](arg1, arg2, arg3);
}

export function ReviewBook() {
  return window['go']['app']['App']['ReviewBook']();
}

export function RunModule(arg1, arg2, arg3) {
  return window['go']['app']['App']['RunModule'](arg1, arg2, arg3);
}

export function SaveAllWorldviewSections(arg1) {
  return window['go']['app']['App']['SaveAllWorldviewSections'](arg1);
}

export function SaveChapterBranchContent(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveChapterBranchContent'](arg1, arg2, arg3);
}

export function SaveChapterContent(arg1, arg2) {
  return window['go']['app']['App']['SaveChapterContent'](arg1, arg2);
}

export function SaveCharacter(arg1) {
  return window['go']['app']['App']['SaveCharacter'](arg1);
}

export function SaveCharacters(arg1) {
  return window['go']['app']['App']['SaveCharacters'](arg1);
}

export function SaveCharactersBatch(arg1) {
  return window['go']['app']['App']['SaveCharactersBatch'](arg1);
}

export function SaveConfig(arg1, arg2) {
  return window['go']['app']['App']['SaveConfig'](arg1, arg2);
}

export function SaveEngine(arg1) {
  return window['go']['app']['App']['SaveEngine'](arg1);
}

export function SaveLorebookEntry(arg1) {
  return window['go']['app']['App']['SaveLorebookEntry'](arg1);
}

export function SaveOrganization(arg1) {
  return window['go']['app']['App']['SaveOrganization'](arg1);
}

export function SaveOutlineNode(arg1) {
  return window['go']['app']['App']['SaveOutlineNode'](arg1);
}

export function SaveRelationship(arg1) {
  return window['go']['app']['App']['SaveRelationship'](arg1);
}

export function SaveScene(arg1, arg2, arg3) {
  return window['go']['app']['App']['SaveScene'](arg1, arg2, arg3);
}

export function SaveTTSConfig(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['app']['App']['SaveTTSConfig'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveToken(arg1) {
  return window['go']['app']['App']['SaveToken'](arg1);
}

export function SaveWorldMapImage(arg1) {
  return window['go']['app']['App']['SaveWorldMapImage'](arg1);
}

export function SaveWorldview(arg1) {
  return window['go']['app']['App']['SaveWorldview'](arg1);
}

export function SaveWorldviewSection(arg1, arg2) {
  return window['go']['app']['App']['SaveWorldviewSection'](arg1, arg2);
}

export function Search(arg1) {
  return window['go']['app']['App']['Search'](arg1);
}

export function SearchMemories(arg1, arg2) {
  return window['go']['app']['App']['SearchMemories'](arg1, arg2);
}

export function SetActiveASRModel(arg1, arg2) {
  return window['go']['app']['App']['SetActiveASRModel'](arg1, arg2);
}

export function SetActiveEngine(arg1) {
  return window['go']['app']['App']['SetActiveEngine'](arg1);
}

export function SetActiveTTSModel(arg1, arg2) {
  return window['go']['app']['App']['SetActiveTTSModel'](arg1, arg2);
}

export function SetCharacterPortrait(arg1, arg2) {
  return window['go']['app']['App']['SetCharacterPortrait'](arg1, arg2);
}

export function SetChatVoiceModel(arg1, arg2) {
  return window['go']['app']['App']['SetChatVoiceModel'](arg1, arg2);
}

export function SetDeepseekKey(arg1) {
  return window['go']['app']['App']['SetDeepseekKey'](arg1);
}

export function SetDistFS(arg1) {
  return window['go']['app']['App']['SetDistFS'](arg1);
}

export function SetEngineDefaultModel(arg1, arg2) {
  return window['go']['app']['App']['SetEngineDefaultModel'](arg1, arg2);
}

export function SetFeatureModel(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetFeatureModel'](arg1, arg2, arg3);
}

export function SetFeatureModelEnabled(arg1, arg2) {
  return window['go']['app']['App']['SetFeatureModelEnabled'](arg1, arg2);
}

export function SetImageBackend(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SetImageBackend'](arg1, arg2, arg3, arg4);
}

export function SetOpencodeGoKey(arg1) {
  return window['go']['app']['App']['SetOpencodeGoKey'](arg1);
}

export function SetOpencodeZenKey(arg1) {
  return window['go']['app']['App']['SetOpencodeZenKey'](arg1);
}

export function SetPortraitConfig(arg1, arg2) {
  return window['go']['app']['App']['SetPortraitConfig'](arg1, arg2);
}

export function StartComfyUI() {
  return window['go']['app']['App']['StartComfyUI']();
}

export function StartLocalTTSService(arg1) {
  return window['go']['app']['App']['StartLocalTTSService'](arg1);
}

export function StartTTSServer(arg1, arg2, arg3) {
  return window['go']['app']['App']['StartTTSServer'](arg1, arg2, arg3);
}

export function StopComfyUI() {
  return window['go']['app']['App']['StopComfyUI']();
}

export function StopTTSServer() {
  return window['go']['app']['App']['StopTTSServer']();
}

export function SyncEntityDB() {
  return window['go']['app']['App']['SyncEntityDB']();
}

export function TTSSpeak(arg1) {
  return window['go']['app']['App']['TTSSpeak'](arg1);
}

export function TTSSpeakBase64(arg1) {
  return window['go']['app']['App']['TTSSpeakBase64'](arg1);
}

export function TTSSpeakStreaming(arg1) {
  return window['go']['app']['App']['TTSSpeakStreaming'](arg1);
}

export function TestEngineConnection(arg1) {
  return window['go']['app']['App']['TestEngineConnection'](arg1);
}

export function ToggleOrgMember(arg1, arg2) {
  return window['go']['app']['App']['ToggleOrgMember'](arg1, arg2);
}

export function VoiceApplySettings(arg1) {
  return window['go']['app']['App']['VoiceApplySettings'](arg1);
}

export function VoiceCancelTTS() {
  return window['go']['app']['App']['VoiceCancelTTS']();
}

export function VoiceChatText(arg1) {
  return window['go']['app']['App']['VoiceChatText'](arg1);
}

export function VoiceGetSettings() {
  return window['go']['app']['App']['VoiceGetSettings']();
}

export function VoiceGetState() {
  return window['go']['app']['App']['VoiceGetState']();
}

export function VoiceHealth() {
  return window['go']['app']['App']['VoiceHealth']();
}

export function VoicePlaybackDone() {
  return window['go']['app']['App']['VoicePlaybackDone']();
}

export function VoicePushAudio(arg1) {
  return window['go']['app']['App']['VoicePushAudio'](arg1);
}

export function VoiceRestartService() {
  return window['go']['app']['App']['VoiceRestartService']();
}

export function VoiceSetInputChannel(arg1) {
  return window['go']['app']['App']['VoiceSetInputChannel'](arg1);
}

export function VoiceSetMode(arg1) {
  return window['go']['app']['App']['VoiceSetMode'](arg1);
}

export function VoiceSetPTTActive(arg1) {
  return window['go']['app']['App']['VoiceSetPTTActive'](arg1);
}

export function VoiceStart(arg1) {
  return window['go']['app']['App']['VoiceStart'](arg1);
}

export function VoiceStop() {
  return window['go']['app']['App']['VoiceStop']();
}

export function WhisperAssistantDelete(arg1) {
  return window['go']['app']['App']['WhisperAssistantDelete'](arg1);
}

export function WhisperAssistantList() {
  return window['go']['app']['App']['WhisperAssistantList']();
}

export function WhisperAssistantSave(arg1) {
  return window['go']['app']['App']['WhisperAssistantSave'](arg1);
}

export function WhisperChat(arg1, arg2) {
  return window['go']['app']['App']['WhisperChat'](arg1, arg2);
}

export function WhisperChatWithSearch(arg1, arg2) {
  return window['go']['app']['App']['WhisperChatWithSearch'](arg1, arg2);
}

export function WhisperClearSession(arg1) {
  return window['go']['app']['App']['WhisperClearSession'](arg1);
}

export function WhisperDeleteFact(arg1, arg2) {
  return window['go']['app']['App']['WhisperDeleteFact'](arg1, arg2);
}

export function WhisperGetConfig() {
  return window['go']['app']['App']['WhisperGetConfig']();
}

export function WhisperGetEngine() {
  return window['go']['app']['App']['WhisperGetEngine']();
}

export function WhisperGetEngines() {
  return window['go']['app']['App']['WhisperGetEngines']();
}

export function WhisperGetFacts(arg1) {
  return window['go']['app']['App']['WhisperGetFacts'](arg1);
}

export function WhisperGetImageModel() {
  return window['go']['app']['App']['WhisperGetImageModel']();
}

export function WhisperGetModel() {
  return window['go']['app']['App']['WhisperGetModel']();
}

export function WhisperGetPersonalities() {
  return window['go']['app']['App']['WhisperGetPersonalities']();
}

export function WhisperGetState(arg1) {
  return window['go']['app']['App']['WhisperGetState'](arg1);
}

export function WhisperGetTraces(arg1) {
  return window['go']['app']['App']['WhisperGetTraces'](arg1);
}

export function WhisperSetAdultMode(arg1, arg2) {
  return window['go']['app']['App']['WhisperSetAdultMode'](arg1, arg2);
}

export function WhisperSetEngine(arg1) {
  return window['go']['app']['App']['WhisperSetEngine'](arg1);
}

export function WhisperSetImageModel(arg1) {
  return window['go']['app']['App']['WhisperSetImageModel'](arg1);
}

export function WhisperSetModel(arg1, arg2) {
  return window['go']['app']['App']['WhisperSetModel'](arg1, arg2);
}

export function WhisperUpdateFact(arg1, arg2, arg3) {
  return window['go']['app']['App']['WhisperUpdateFact'](arg1, arg2, arg3);
}

export function WhisperWebSearch(arg1) {
  return window['go']['app']['App']['WhisperWebSearch'](arg1);
}

export function WhisperWeixinGetQR() {
  return window['go']['app']['App']['WhisperWeixinGetQR']();
}

export function WhisperWeixinQRStatus(arg1) {
  return window['go']['app']['App']['WhisperWeixinQRStatus'](arg1);
}

export function WhisperWeixinQRStatusWithCode(arg1, arg2) {
  return window['go']['app']['App']['WhisperWeixinQRStatusWithCode'](arg1, arg2);
}

export function WhisperWeixinStatus() {
  return window['go']['app']['App']['WhisperWeixinStatus']();
}
